const TRACKS = {
  "digital-currencies": {
    type: "leveled",
    title: "مسار العملات الرقمية", title_en: "Digital Currencies Path",
    levels: [
      {
        id: "beginner",
        name: "المستوى الأساسي", name_en: "Beginner Level",
        badge: "مبتدئ",
        lessons: [
          {id:"b1", title:"ما هي العملات الرقمية", title_en:"What Are Cryptocurrencies?", content_en:"Cryptocurrencies are purely digital financial assets with no physical form. Built on blockchain technology, they let people record and transfer ownership directly between each other without a bank or middleman. Bitcoin, launched in 2009, was the first.", content:"العملات الرقمية هي أصول مالية إلكترونية بحتة، لا وجود لها كأوراق نقدية أو معادن، وتُبنى على تقنية تسمح بتسجيل الملكية ونقلها بين الأشخاص مباشرة دون الحاجة لبنك أو وسيط. تُخزَّن في محافظ رقمية، ويمكن استخدامها للدفع أو الاستثمار أو تشغيل تطبيقات لامركزية، وأشهرها البيتكوين الذي ظهر عام 2009 كأول عملة رقمية في العالم.", quiz:{q:"العملات الرقمية تعتمد أساساً على:",options:["ورق نقدي مطبوع","تقنية البلوكتشين","موافقة بنك مركزي واحد","لا شيء تقني"],correct:1,q_en:"Cryptocurrencies are fundamentally built on:",options_en:["Printed paper money","Blockchain technology","One central bank's approval","Nothing technical"]}},
          {id:"b2", title:"مقارنة بين العملات الرقمية والعملات العادية (مميزات وعيوب كل صنف)", title_en:"Crypto vs. Traditional Money: Pros & Cons", content_en:"Traditional money (fiat) is issued by a central bank, backed by government trust, relatively stable, but subject to inflation and central control. Crypto is decentralized, often has a capped supply, and enables fast cross-border transfers, but is more volatile and less legally protected in many countries.", content:"العملة العادية (الفيات) يصدرها البنك المركزي ويضمن قيمتها، وتخضع لرقابة الدولة، وتتميز باستقرار نسبي وقبول واسع، لكنها عرضة للتضخم والتحكم المركزي. العملة الرقمية لا مركزية، عرضها محدود في الغالب، وتتيح تحويلات سريعة عبر الحدود دون وسيط، لكنها أكثر تقلباً في السعر وأقل حماية قانونية في كثير من الدول حتى الآن.", quiz:{q:"عيوب العملات الرقمية غالباً تشمل:",options:["استقرار سعري تام","تقلب سعري أعلى من الفيات","رقابة بنكية كاملة","لا عيوب إطلاقاً"],correct:1,q_en:"A common drawback of cryptocurrencies is:",options_en:["Perfect price stability","Higher volatility than fiat","Full bank oversight","No drawbacks at all"]}},
          {id:"b3", title:"لماذا العملات الرقمية الخيار الأفضل", title_en:"Why Crypto Can Be the Better Choice", content_en:"Crypto enables faster, cheaper cross-border payments, reaches anyone with just an internet connection, and offers full transparency since every transaction is recorded on the blockchain. It also gives users complete control over their funds without a middleman able to freeze an account.", content:"توفر العملات الرقمية تحويلات مالية أسرع وأرخص عبر الحدود، وإمكانية الوصول لأي شخص لديه اتصال بالإنترنت فقط دون حاجة لحساب بنكي، وشفافية كاملة في تتبع المعاملات عبر البلوكتشين. كما تمنح المستخدم تحكماً كاملاً في أمواله دون وسيط يمكنه تجميد الحساب أو رفض العملية.", quiz:{q:"من أبرز مزايا العملات الرقمية:",options:["تحويلات أبطأ من البنوك دائماً","تحويلات سريعة عبر الحدود","تحتاج حساباً بنكياً إلزامياً","تحكم كامل من طرف ثالث"],correct:1,q_en:"A key advantage of crypto is:",options_en:["Always slower transfers than banks","Fast cross-border transfers","A mandatory bank account","Full third-party control of funds"]}},
          {id:"b4", title:"التشفير في العملات الرقمية", title_en:"Encryption in Cryptocurrencies", content_en:"Crypto security relies on cryptography — specifically public and private keys. Your public key is like an account number you share; your private key is the secret signature that proves ownership and authorizes transactions. This makes forging transactions or identity theft mathematically near-impossible.", content:"يعتمد أمان العملات الرقمية على علم التشفير (Cryptography)، وتحديداً المفاتيح العامة والخاصة: المفتاح العام أشبه برقم حسابك الذي تشاركه، والمفتاح الخاص هو التوقيع السري الذي يثبت ملكيتك وينفّذ العمليات. هذا التشفير يجعل تزوير المعاملات أو انتحال الهوية شبه مستحيل رياضياً.", quiz:{q:"المفتاح الخاص في التشفير يُستخدم من أجل:",options:["مشاركته علناً","توقيع المعاملات وإثبات الملكية","تغيير اسم العملة","لا فائدة له"],correct:1,q_en:"A private key in crypto is used to:",options_en:["Share it publicly","Sign transactions and prove ownership","Rename the coin","It has no use"]}},
          {id:"b5", title:"ما هو الكريبتو", title_en:"What Is Crypto?", content_en:"\"Crypto\" is shorthand for \"cryptocurrency\" and is used as an umbrella term for all digital assets built on blockchain and cryptography — not just Bitcoin. It also refers to the whole economic sector around them: trading, platforms, projects, and decentralized apps.", content:"كريبتو (Crypto) اختصار شائع لمصطلح 'العملات المشفّرة'، ويُستخدم كمظلة تشمل كل العملات والأصول الرقمية المبنية على تقنية البلوكتشين والتشفير، وليس فقط البيتكوين. يشمل المصطلح أيضاً القطاع الاقتصادي الكامل المرتبط بها: التداول، المنصات، المشاريع، والتطبيقات اللامركزية.", quiz:{q:"مصطلح \"كريبتو\" يشير إلى:",options:["البيتكوين فقط","كل الأصول الرقمية المشفرة عموماً","نوع من البنوك","عملة ورقية"],correct:1,q_en:"The term \"crypto\" refers to:",options_en:["Bitcoin only","All encrypted digital assets in general","A type of bank","Paper currency"]}},
          {id:"b6", title:"ما هو البيتكوين", title_en:"What Is Bitcoin?", content_en:"Bitcoin is the first decentralized cryptocurrency ever created, launched in 2009 as a peer-to-peer electronic payment system that needs no bank intermediary. Its supply is capped at 21 million coins, a built-in scarcity that leads many investors to call it \"digital gold.\"", content:"البيتكوين هو أول عملة رقمية لا مركزية في التاريخ، أطلقها شخص أو مجموعة تحت اسم مستعار 'ساتوشي ناكاموتو' عام 2009. يعمل بدون أي جهة مركزية تتحكم به، وعرضه محدود بـ 21 مليون عملة فقط، وهو ما يجعله يُشبَّه غالباً بـ'الذهب الرقمي' كمخزن للقيمة.", quiz:{q:"الحد الأقصى لعدد عملات البيتكوين هو:",options:["غير محدود","100 مليون","21 مليون","1 مليار"],correct:2,q_en:"Bitcoin's maximum supply is capped at:",options_en:["Unlimited","100 million","21 million","1 billion"]}},
          {id:"b7", title:"ما هي الشبكات الرقمية", title_en:"What Are Digital Networks?", content_en:"A crypto network is the underlying blockchain infrastructure a coin or group of applications runs on, made up of thousands of computers (nodes) worldwide that verify and store transactions. Examples include the Bitcoin network and the Ethereum network, each with its own rules, speed, and fees.", content:"الشبكة الرقمية في عالم الكريبتو هي البنية التحتية (البلوكتشين) التي تعمل عليها عملة أو مجموعة عملات، مكوّنة من آلاف الأجهزة (العُقَد) حول العالم تتحقق من صحة المعاملات وتخزّنها بشكل موزّع. أمثلة: شبكة بيتكوين، شبكة إيثريوم، وكل شبكة لها قواعدها وسرعتها ورسومها الخاصة.", quiz:{q:"العُقد (Nodes) في الشبكة الرقمية وظيفتها:",options:["طباعة العملات","التحقق من المعاملات وتخزينها","تحديد سعر العملة يدوياً","لا وظيفة لها"],correct:1,q_en:"Nodes in a blockchain network mainly:",options_en:["Print new coins","Verify and store transactions","Manually set the coin price","Have no function"]}},
          {id:"b8", title:"أنواع العملات الرقمية", title_en:"Types of Cryptocurrencies", content_en:"Broadly, cryptocurrencies fall into: base coins with their own network (like Bitcoin and Ethereum), stablecoins pegged to a traditional currency like the dollar, and tokens built on top of other networks for specific purposes like governance or access to a service.", content:"تنقسم العملات الرقمية بشكل عام إلى: عملات أساسية لها شبكتها الخاصة (مثل بيتكوين وإيثريوم)، وعملات مستقرة (Stablecoins) مربوطة بعملة تقليدية مثل الدولار، وتوكنات مبنية فوق شبكات أخرى لأغراض محددة مثل الحوكمة أو الوصول لخدمة معينة. سنتعمق في تصنيفات أدق في المستوى المتوسط.", quiz:{q:"العملات المستقرة (Stablecoins) عادة مربوطة بـ:",options:["سعر الذهب فقط","عملة تقليدية مثل الدولار","لا ترتبط بشيء","سعر النفط"],correct:1,q_en:"Stablecoins are usually pegged to:",options_en:["Gold price only","A traditional currency like the dollar","Nothing at all","Oil price"]}},
          {id:"b9", title:"أنواع منصات التداول", title_en:"Types of Trading Platforms", content_en:"Crypto trading platforms split into two main types: centralized exchanges (CEX) run by a company that acts as a middleman for a fee, offering ease of use and high liquidity; and decentralized exchanges (DEX) that work through smart contracts directly between users, giving more control but requiring more technical skill.", content:"تنقسم منصات تداول العملات الرقمية إلى نوعين رئيسيين: منصات مركزية (CEX) تديرها شركة وتتوسط بين المشترين والبائعين مقابل رسوم، وتتميز بالسهولة والسيولة العالية؛ ومنصات لامركزية (DEX) تعمل عبر عقود ذكية مباشرة بين المستخدمين دون شركة وسيطة، وتمنح تحكماً أكبر لكن تتطلب خبرة تقنية أعلى.", quiz:{q:"الفرق الجوهري بين CEX و DEX هو:",options:["لا فرق بينهما","CEX وسيط يحتفظ بأموالك، DEX تتداول مباشرة من محفظتك","DEX فقط للبيتكوين","CEX غير قانونية"],correct:1,q_en:"The core difference between CEX and DEX:",options_en:["No real difference","CEX holds your funds as intermediary, DEX trades directly from your wallet","DEX is Bitcoin-only","CEX is illegal"]}},
          {id:"b10", title:"خاتمة", title_en:"Conclusion", content_en:"You've now completed the beginner level with a clear picture of what cryptocurrencies are, how they differ from traditional money, the basics of encryption and networks, and the types of trading platforms. This foundation is essential before moving to the intermediate level's deeper coin categories and platform types.", content:"بهذا تكون قد أنهيت المستوى الأساسي، وأصبح لديك فهم واضح لماهية العملات الرقمية، والفرق بينها وبين العملات التقليدية، وأساسيات التشفير والشبكات وأنواع المنصات. هذه القاعدة ضرورية قبل الانتقال للمستوى المتوسط حيث ستتعرف على تصنيفات أعمق للعملات وأنواع المنصات.", quiz:{q:"بعد إكمال المستوى الأساسي، الخطوة التالية هي:",options:["التوقف عن التعلم","الانتقال للمستوى المتوسط","حذف المحفظة","لا شيء"],correct:1,q_en:"After finishing the beginner level, the next step is:",options_en:["Stop learning","Move to the intermediate level","Delete your wallet","Nothing"]}}
        ],
        exam: {
          pass: 60,
          questions: [
            {q:"من أطلق أول عملة رقمية (البيتكوين)؟", options:["بنك مركزي دولي","شخص أو مجموعة تحت اسم ساتوشي ناكاموتو","شركة جوجل","لا أحد يعرف حتى الآن"], correct:1},
            {q:"ما الحد الأقصى لعدد عملات البيتكوين؟", options:["بلا حد أقصى","100 مليون","21 مليون","1 مليار"], correct:2},
            {q:"ما الفرق الأساسي بين CEX و DEX؟", options:["لا فرق بينهما","CEX تديرها شركة وسيطة، DEX تعمل عبر عقود ذكية مباشرة","DEX فقط للبيتكوين","CEX غير قانونية"], correct:1},
            {q:"المفتاح الخاص في المحفظة الرقمية يُستخدم من أجل:", options:["مشاركته مع الأصدقاء","إثبات الملكية وتوقيع المعاملات","تغيير اسم العملة","الإعلان عن رصيدك"], correct:1},
            {q:"العملات المستقرة (Stablecoins) مربوطة عادة بـ:", options:["سعر الذهب فقط","عملة تقليدية مثل الدولار","سعر النفط","لا ترتبط بأي شيء"], correct:1}
          ]
        }
      },
      {
        id: "intermediate",
        name: "المستوى المتوسط", name_en: "Intermediate Level",
        badge: "متوسط",
        lessons: [
          {id:"i1", title:"التشفير في البيتكوين", title_en:"Encryption in Bitcoin", content_en:"The Bitcoin network relies on the SHA-256 hashing algorithm to secure transactions and link blocks into a chain that can't be altered without recomputing the entire network's work. It also uses \"Proof of Work,\" requiring miners to solve complex calculations to add a new block, giving the network its decentralized security.", content:"تعتمد شبكة البيتكوين على خوارزمية تشفير SHA-256 لتأمين المعاملات وربط الكتل ببعضها في سلسلة يستحيل تعديلها دون إعادة حساب كل الشبكة. كما تعتمد على آلية 'إثبات العمل' (Proof of Work) التي تتطلب من المعدّنين حل مسائل حسابية معقدة لإضافة كتلة جديدة، وهو ما يمنح الشبكة أمانها اللامركزي.", image_url:"https://picsum.photos/seed/aw100/800/450", quiz:{q:"خوارزمية التشفير المستخدمة في شبكة البيتكوين هي:",options:["MD5","SHA-256","AES-128","RSA فقط"],correct:1,q_en:"The hashing algorithm used in the Bitcoin network is:",options_en:["MD5","SHA-256","AES-128","RSA only"]}},
          {id:"i2", title:"أنواع العملات الرقمية (عملات الميم)", title_en:"Coin Types: Meme Coins", content_en:"Meme coins launch from an internet joke or pop culture reference more than a technical project — Dogecoin and Shiba Inu are prime examples. Their value depends heavily on community hype rather than real utility, making them extremely volatile and high-risk compared to fundamentally-driven coins.", content:"عملات الميم (Meme Coins) هي عملات تنطلق غالباً من نكتة أو ثقافة إنترنت شهيرة أكثر من كونها مشروعاً تقنياً، مثل Dogecoin و Shiba Inu. تعتمد قيمتها بشكل كبير على المجتمع والحماس الجماهيري أكثر من استخدام فعلي، لذلك تتميز بتقلب سعري حاد وتحمل مخاطرة مرتفعة جداً مقارنة بالعملات ذات الأساس التقني.", quiz:{q:"عملات الميم تعتمد قيمتها أساساً على:",options:["تقنية معقدة فريدة","حماس المجتمع والثقافة الشائعة","دعم حكومي مباشر","احتياطي ذهب"],correct:1,q_en:"Meme coins derive their value mainly from:",options_en:["A unique complex technology","Community hype and pop culture","Direct government backing","A gold reserve"]}},
          {id:"i3", title:"أنواع العملات الرقمية (دي فاي)", title_en:"Coin Types: DeFi", content_en:"DeFi-related tokens are tied to platforms offering financial services — lending, borrowing, trading, yield — through smart contracts instead of a traditional bank. Holders of these tokens often get voting rights on platform decisions (governance) or a share of the protocol's revenue.", content:"عملات وتوكنات DeFi (التمويل اللامركزي) هي تلك المرتبطة بمنصات تقدّم خدمات مالية (إقراض، اقتراض، تبادل، عائد استثماري) عبر عقود ذكية بدون بنك تقليدي. حاملو هذه التوكنات غالباً يملكون حق التصويت على قرارات المنصة (الحوكمة) أو حصة من أرباح البروتوكول.", video_url:"https://developer.mozilla.org/shared-assets/videos/flower.mp4", quiz:{q:"توكنات DeFi غالباً تمنح حاملها:",options:["حق التصويت على الحوكمة","ملكية عقارية","جواز سفر","لا شيء"],correct:0,q_en:"DeFi tokens often grant holders:",options_en:["Governance voting rights","Real estate ownership","A passport","Nothing"]}},
          {id:"i4", title:"أنواع العملات الرقمية (الذكاء الاصطناعي)", title_en:"Coin Types: AI Coins", content_en:"AI coin projects blend blockchain with artificial intelligence technology — for example, running decentralized computing networks to train AI models, or platforms that let you buy and sell AI services using crypto. This sector has grown notably alongside global interest in AI.", content:"فئة عملات الذكاء الاصطناعي (AI Coins) ترتبط بمشاريع تدمج بين البلوكتشين وتقنيات الذكاء الاصطناعي، مثل تشغيل شبكات حوسبة لامركزية لتدريب النماذج، أو منصات تتيح شراء وبيع خدمات ذكاء اصطناعي بالعملة الرقمية. هذا القطاع نما بشكل ملحوظ مع تصاعد الاهتمام العالمي بالذكاء الاصطناعي.", quiz:{q:"عملات الذكاء الاصطناعي ترتبط بـ:",options:["الزراعة التقليدية","دمج البلوكتشين مع تقنيات الذكاء الاصطناعي","العملات الورقية فقط","لا علاقة لها بالتقنية"],correct:1,q_en:"AI coins are tied to:",options_en:["Traditional agriculture","Blending blockchain with AI technology","Paper currency only","Nothing technical"]}},
          {id:"i5", title:"أنواع العملات الرقمية (الرياضية)", title_en:"Coin Types: Sports/Fan Tokens", content_en:"Sports sector tokens (Fan Tokens) are issued by clubs or sports organizations, giving holders perks like voting on minor decisions, exclusive content, or discounts on official merchandise. Their value is usually tied to the club's or event's popularity rather than any deep new technology.", content:"عملات القطاع الرياضي (Fan Tokens) تصدرها أندية أو جهات رياضية لتمنح مالكيها امتيازات مثل التصويت على قرارات بسيطة، محتوى حصري، أو خصومات على المنتجات الرسمية. قيمتها ترتبط غالباً بشعبية النادي أو الحدث الرياضي أكثر من ارتباطها بتقنية جوهرية جديدة.", quiz:{q:"Fan Tokens الرياضية قيمتها ترتبط غالباً بـ:",options:["شعبية النادي أو الحدث","سعر النفط","تقنية جديدة جذرية","لا شيء"],correct:0,q_en:"Sports Fan Tokens' value is usually tied to:",options_en:["The club's or event's popularity","Oil prices","A radically new technology","Nothing"]}},
          {id:"i6", title:"أنواع العملات الرقمية (تراي دفاي)", title_en:"Coin Types: TriFi", content_en:"TriFi (\"triple finance\") is a concept blending three elements — traditional finance (TradFi), decentralized finance (DeFi), and centralized platform finance (CeFi) — into a single protocol trying to capture the benefits of all three, such as linking real-world assets to DeFi products.", content:"TriFi أو 'التمويل الثلاثي' مفهوم يجمع بين ثلاثة عناصر: التمويل التقليدي (TradFi)، التمويل اللامركزي (DeFi)، والتمويل المركزي عبر المنصات (CeFi)، في منتج أو بروتوكول واحد يحاول الاستفادة من مزايا الأنظمة الثلاثة معاً، مثل ربط أصول حقيقية بمنتجات DeFi.", quiz:{q:"TriFi يجمع بين:",options:["التمويل التقليدي، DeFi، وCeFi","الرياضة والتعليم فقط","لا شيء تقني","الذهب والفضة"],correct:0,q_en:"TriFi blends together:",options_en:["Traditional finance, DeFi, and CeFi","Sports and education only","Nothing technical","Gold and silver"]}},
          {id:"i7", title:"أنواع العملات الرقمية (لاير ون)", title_en:"Coin Types: Layer 1", content_en:"Layer 1 coins belong to independent base networks like Ethereum, Solana, and Bitcoin, where transactions are processed directly on their own chain without relying on another network. These chains are the foundation most other applications and tokens are built on top of.", content:"عملات الطبقة الأولى (Layer 1) هي عملات الشبكات الأساسية المستقلة بذاتها، مثل إيثريوم وسولانا وبيتكوين، حيث تُعالَج المعاملات مباشرة على شبكتها دون الاعتماد على شبكة أخرى. هذه الشبكات هي الأساس الذي تُبنى فوقه معظم التطبيقات والتوكنات الأخرى.", image_url:"https://picsum.photos/seed/aw101/800/450", quiz:{q:"عملات Layer 1 مثل إيثريوم وسولانا:",options:["تعمل على شبكتها المستقلة","تعتمد بالكامل على شبكة أخرى","لا تمتلك شبكة إطلاقاً","هي نوع من stablecoins"],correct:0,q_en:"Layer 1 coins like Ethereum and Solana:",options_en:["Run on their own independent network","Fully depend on another network","Have no network at all","Are a type of stablecoin"]}},
          {id:"i8", title:"أنواع العملات الرقمية (لاير تو)", title_en:"Coin Types: Layer 2", content_en:"Layer 2 coins are solutions built on top of a Layer 1 network to speed up transactions and cut fees, by processing part of the work off-chain and then recording a summary back on the base chain. Arbitrum and Optimism, both built on Ethereum, are examples.", content:"عملات الطبقة الثانية (Layer 2) هي حلول تُبنى فوق شبكة Layer 1 لتسريع المعاملات وتقليل رسومها، عبر معالجة جزء من العمليات خارج الشبكة الأساسية ثم تسجيل ملخصها عليها. أمثلة: Arbitrum و Optimism المبنيتان فوق إيثريوم.", quiz:{q:"الهدف الأساسي من حلول Layer 2 هو:",options:["زيادة الرسوم عمداً","تسريع المعاملات وخفض الرسوم","إلغاء الطبقة الأولى","تخزين الصور"],correct:1,q_en:"The main purpose of Layer 2 solutions is:",options_en:["Deliberately raising fees","Speeding up transactions and cutting fees","Eliminating Layer 1","Storing images"]}},
          {id:"i9", title:"أنواع العملات الرقمية (القيمنق)", title_en:"Coin Types: GameFi", content_en:"GameFi tokens combine gaming with decentralized finance, where players earn coins or digital assets (like NFTs) that carry real trading value for their in-game achievements — unlike traditional games where rewards stay locked inside the game itself.", content:"عملات GameFi تجمع بين الألعاب والتمويل اللامركزي، حيث يكسب اللاعب عملات أو أصولاً رقمية (مثل NFTs) قابلة للتداول الحقيقي مقابل إنجازه داخل اللعبة، بعكس الألعاب التقليدية التي تبقى مكافآتها حبيسة داخل اللعبة فقط.", quiz:{q:"GameFi يجمع بين:",options:["الألعاب والتمويل اللامركزي","البنوك التقليدية والتأمين","الذهب والعقارات","لا علاقة له بالكريبتو"],correct:0,q_en:"GameFi combines:",options_en:["Gaming and decentralized finance","Traditional banks and insurance","Gold and real estate","Nothing related to crypto"]}},
          {id:"i10", title:"أنواع العملات الرقمية (الفاء)", title_en:"Coin Types: \"Fi\" Sector Projects", content_en:"This category covers projects with the \"Fi\" suffix tied to a specific sector blended with decentralized finance, such as SocialFi, which connects social media platforms to on-chain rewards for users based on their engagement and content.", content:"تشمل هذه الفئة مشاريع تحمل لاحقة 'Fi' المرتبطة بقطاعات محددة تدمج بين نشاط تقليدي والتمويل اللامركزي، مثل SocialFi التي تربط منصات التواصل الاجتماعي بمكافآت رقمية للمستخدمين مقابل تفاعلهم ومحتواهم.", quiz:{q:"مشاريع \"الفاء\" (Fi) غالباً تدمج قطاعاً تقليدياً مع:",options:["التمويل اللامركزي","الزراعة العضوية فقط","لا شيء","الطباعة ثلاثية الأبعاد"],correct:0,q_en:"\"Fi\"-suffixed projects usually blend a traditional sector with:",options_en:["Decentralized finance","Organic farming only","Nothing","3D printing"]}},
          {id:"i11", title:"أنواع العملات الرقمية (NFT)", title_en:"Coin Types: NFTs", content_en:"NFTs (non-fungible tokens) are unique tokens where no single unit is interchangeable with another identical one — unlike Bitcoin, where every unit is equal. They're used to prove ownership of digital art, an in-game item, or even membership in a private community.", content:"NFT (الأصول غير القابلة للاستبدال) هي توكنات فريدة لا يمكن استبدال الواحدة منها بأخرى مطابقة، بعكس البيتكوين مثلاً حيث كل وحدة مطابقة للأخرى. تُستخدم لإثبات ملكية عمل فني رقمي، عنصر داخل لعبة، أو حتى عضوية في مجتمع مغلق.", image_url:"https://picsum.photos/seed/aw102/800/450", quiz:{q:"خاصية NFT الجوهرية هي:",options:["قابلة للاستبدال دائماً بعملة أخرى مطابقة","غير قابلة للاستبدال، كل وحدة فريدة","نوع من stablecoins","خاصة بالبيتكوين فقط"],correct:1,q_en:"The core property of an NFT is:",options_en:["Always interchangeable with an identical coin","Non-fungible — each unit is unique","A type of stablecoin","Exclusive to Bitcoin"]}},
          {id:"i12", title:"المنصات المركزية", title_en:"Centralized Platforms", content_en:"Centralized exchanges (CEX) like Binance and OKX act as an intermediary between you and the market: they hold your funds, offering high liquidity, ease of use, and customer support — but require trusting the platform itself, and any technical or legal issue there can affect your access to your money.", content:"المنصات المركزية (CEX) مثل بينانس وأوكيه إكس تعمل كوسيط بينك وبين السوق: تحتفظ بأموالك في حساباتها، وتوفّر سيولة عالية وسهولة استخدام وخدمة عملاء، لكنها تتطلب ثقة بالمنصة نفسها، وأي مشكلة تقنية أو قانونية بها قد تؤثر على وصولك لأموالك.", quiz:{q:"في المنصات المركزية (CEX)، من يحتفظ فعلياً بأموالك؟",options:["أنت فقط","المنصة نفسها","لا أحد","الحكومة"],correct:1,q_en:"On centralized platforms (CEX), who actually holds your funds?",options_en:["You alone","The platform itself","No one","The government"]}},
          {id:"i13", title:"المنصات اللامركزية", title_en:"Decentralized Platforms", content_en:"Decentralized exchanges (DEX) like Uniswap let you trade directly from your own wallet via smart contracts, without handing your funds to anyone — giving full control and stronger privacy, but requiring more technical understanding and putting the responsibility for any mistake or lost key entirely on you.", content:"المنصات اللامركزية (DEX) مثل Uniswap تتيح التداول مباشرة من محفظتك عبر عقود ذكية دون تسليم أموالك لأي جهة، ما يمنحك تحكماً كاملاً وخصوصية أعلى، لكنها تتطلب فهماً تقنياً أكبر، وتحمّلك أنت وحدك مسؤولية أي خطأ في المعاملة أو فقدان المفتاح الخاص.", quiz:{q:"في المنصات اللامركزية (DEX)، التداول يتم:",options:["عبر موظف بشري","مباشرة من محفظتك عبر عقود ذكية","بالبريد فقط","عبر مكالمة هاتفية"],correct:1,q_en:"On decentralized platforms (DEX), trading happens:",options_en:["Through a human employee","Directly from your wallet via smart contracts","By mail only","Over a phone call"]}}
        ],
        exam: {
          pass: 60,
          questions: [
            {q:"عملات الميم (Meme Coins) تعتمد قيمتها بشكل أساسي على:", options:["تقنية معقدة فريدة","حماس المجتمع والثقافة الشائعة","دعم حكومي مباشر","احتياطي ذهب"], correct:1},
            {q:"ما وظيفة الطبقة الثانية (Layer 2)؟", options:["استبدال Layer 1 بالكامل","تسريع المعاملات وتقليل الرسوم فوق شبكة Layer 1","تخزين الصور فقط","لا علاقة لها بالبلوكتشين"], correct:1},
            {q:"NFT تتميز بكونها:", options:["قابلة للاستبدال دائماً بعملة أخرى مطابقة","غير قابلة للاستبدال، كل وحدة فريدة","نوع من العملات المستقرة","خاصة بالبيتكوين فقط"], correct:1},
            {q:"الفرق الجوهري بين CEX و DEX هو:", options:["DEX تحتفظ بأموالك بدلاً منك","CEX وسيط يحتفظ بأموالك، DEX تتداول مباشرة من محفظتك","لا فرق حقيقي","CEX غير موجودة فعلياً"], correct:1},
            {q:"GameFi يجمع بين:", options:["البنوك التقليدية والتأمين","الألعاب والتمويل اللامركزي","الذهب والعقارات","لا علاقة له بالكريبتو"], correct:1}
          ]
        }
      },
      {
        id: "advanced",
        name: "المستوى المتقدم", name_en: "Advanced Level",
        badge: "متقدم",
        lessons: [
          {id:"a1", title:"البلوك تشين", title_en:"Blockchain", content_en:"Blockchain is a digital ledger distributed across thousands of machines worldwide. Transactions are grouped into \"blocks,\" each cryptographically linked to the one before it, making it practically impossible to alter old data without the tampering being detected. This structure gives cryptocurrencies their transparency and tamper-resistance.", content:"البلوك تشين هو سجل رقمي موزّع على آلاف الأجهزة حول العالم، تُجمَّع فيه المعاملات في 'كتل' يرتبط كل منها بالكتلة السابقة عبر تشفير، بحيث يستحيل عملياً تعديل بيانات قديمة دون كشف التلاعب. هذه البنية هي ما يمنح العملات الرقمية شفافيتها ومقاومتها للتزوير.", video_url:"https://developer.mozilla.org/shared-assets/videos/flower.mp4", quiz:{q:"البلوك تشين يجعل تعديل البيانات القديمة:",options:["سهلاً جداً","شبه مستحيل دون كشف فوري","مسموحاً به قانونياً","غير ذي صلة"],correct:1,q_en:"Blockchain makes altering old data:",options_en:["Very easy","Practically impossible without instant detection","Legally permitted","Irrelevant"]}},
          {id:"a2", title:"تقنية البلوك تشين", title_en:"Blockchain Technology", content_en:"Blockchain technology includes consensus mechanisms that determine how thousands of machines agree on which transactions are valid — most notably Proof of Work (used in Bitcoin) and Proof of Stake (used in modern Ethereum), each balancing security, energy use, and transaction speed differently.", content:"تشمل تقنية البلوك تشين آليات إجماع (Consensus) تحدد كيف تتفق آلاف الأجهزة على صحة المعاملات، أبرزها إثبات العمل (Proof of Work) المستخدم في البيتكوين، وإثبات الحصة (Proof of Stake) المستخدم في إيثريوم الحديث، وكل آلية لها موازنة مختلفة بين الأمان واستهلاك الطاقة وسرعة المعاملات.", quiz:{q:"آلية إثبات الحصة (Proof of Stake) تشتهر باستخدامها في:",options:["البيتكوين منذ البداية","إيثريوم الحديث","الذهب الرقمي","لا شبكة تستخدمها"],correct:1,q_en:"Proof of Stake is famously used by:",options_en:["Bitcoin from the start","Modern Ethereum","Digital gold","No network uses it"]}},
          {id:"a3", title:"تقنية الباو (Polkadot)", title_en:"Polkadot Technology", content_en:"Polkadot is a network designed to connect several independent blockchains (called parachains) so they can securely exchange data and assets with each other through one main network called the Relay Chain, instead of each chain operating in complete isolation.", content:"بولكادوت (Polkadot) شبكة مصمّمة لربط عدة بلوكتشينات مستقلة (تسمى Parachains) معاً، بحيث يمكنها تبادل البيانات والأصول فيما بينها بأمان عبر شبكة رئيسية واحدة تسمى Relay Chain، بدل أن تعمل كل شبكة بمعزل تام عن الأخرى.", quiz:{q:"بولكادوت (Polkadot) صُممت أساساً من أجل:",options:["استبدال إيثريوم فقط","ربط عدة بلوكتشينات مستقلة معاً","تخزين الصور فقط","التداول الفوري حصراً"],correct:1,q_en:"Polkadot was designed mainly to:",options_en:["Only replace Ethereum","Connect several independent blockchains","Only store images","Only enable spot trading"]}},
          {id:"a4", title:"تقنية الإيثريوم", title_en:"Ethereum Technology", content_en:"Ethereum is a blockchain network that goes beyond being just a payment coin — it's a decentralized \"world computer\" letting any developer build and run full applications on top of it without a central server owned by anyone.", content:"إيثريوم شبكة بلوكتشين تتيح تشغيل 'عقود ذكية' وتطبيقات لامركزية كاملة فوقها، وليست فقط عملة للدفع. تحوّلت عام 2022 من إثبات العمل إلى إثبات الحصة لخفض استهلاك الطاقة بشكل كبير، وهي البنية التحتية الأساسية لمعظم مشاريع DeFi و NFT اليوم.", image_url:"https://picsum.photos/seed/aw103/800/450", quiz:{q:"إيثريوم يُوصف غالباً بأنه:",options:["مجرد عملة دفع بسيطة","حاسوب عالمي لامركزي","بنك تقليدي","لا علاقة له بالبرمجة"],correct:1,q_en:"Ethereum is often described as:",options_en:["Just a simple payment coin","A decentralized world computer","A traditional bank","Unrelated to programming"]}},
          {id:"a5", title:"أساسيات التداول", title_en:"Trading Basics", content_en:"Trading means buying and selling assets to profit from price differences over the short-to-medium term, relying on understanding supply, demand, liquidity, and volume. Before any trade, you need a clear plan defining your entry point, target, and stop-loss.", content:"التداول هو شراء وبيع الأصول بهدف الربح من فروق الأسعار، ويقوم على فهم العرض والطلب، السيولة، وحجم التداول. قبل أي صفقة، يحتاج المتداول لخطة واضحة تحدد نقطة الدخول، الهدف، ووقف الخسارة، بدل الدخول بناءً على العاطفة أو الشائعات.", quiz:{q:"قبل أي صفقة تداول، يحتاج المتداول لتحديد:",options:["لا شيء مسبقاً","نقطة الدخول والهدف ووقف الخسارة","اسم صديق عشوائي","لون الشاشة"],correct:1,q_en:"Before any trade, a trader needs to define:",options_en:["Nothing in advance","Entry point, target, and stop-loss","A random friend's name","Screen color"]}},
          {id:"a6", title:"طرق التداول", title_en:"Trading Styles", content_en:"Trading styles vary: day trading (opening and closing a position within the same day), swing trading (holding for days or weeks), and long-term investing (HODLing) which means holding for years while ignoring short-term volatility.", content:"تتعدد أساليب التداول: التداول اليومي (فتح وإغلاق الصفقة خلال نفس اليوم)، تداول المراكز الأطول (Swing Trading) الذي يمتد لأيام أو أسابيع، والاستثمار طويل الأمد (HODLing) الذي يعتمد على الاحتفاظ لسنوات متجاهلاً تقلبات السوق قصيرة المدى.", quiz:{q:"HODLing يعني:",options:["بيع وشراء يومي سريع","الاحتفاظ طويل الأمد متجاهلاً التقلبات","إغلاق الحساب فوراً","نوع من العقود الآجلة"],correct:1,q_en:"HODLing means:",options_en:["Fast daily buying and selling","Holding long-term while ignoring volatility","Immediately closing your account","A type of futures contract"]}},
          {id:"a7", title:"الفيوتشر (العقود الآجلة)", title_en:"Futures Contracts", content_en:"Futures contracts let you speculate on a coin's future price without owning it, often using leverage that multiplies potential profits — but multiplies losses by the same amount. This type of trading carries very high risk and requires experience and strict risk management.", content:"عقود الفيوتشر تتيح المضاربة على سعر عملة مستقبلاً دون امتلاكها فعلياً، وغالباً باستخدام رافعة مالية (Leverage) تضاعف الأرباح المحتملة لكنها تضاعف الخسائر بنفس القدر أيضاً. هذا النوع من التداول يحمل مخاطرة مرتفعة جداً ويحتاج خبرة وإدارة مخاطر صارمة.", quiz:{q:"الرافعة المالية في عقود الفيوتشر:",options:["تلغي كل المخاطر","تضاعف الأرباح والخسائر معاً","تضمن الربح دائماً","غير موجودة في الفيوتشر"],correct:1,q_en:"Leverage in futures contracts:",options_en:["Eliminates all risk","Multiplies both gains and losses","Always guarantees profit","Doesn't exist in futures"]}},
          {id:"a8", title:"السبوت (التداول الفوري)", title_en:"Spot Trading", content_en:"Spot trading means buying a coin and actually owning it in your wallet at its current price, with no leverage or future delivery date. It's considered lower risk than futures because the maximum possible loss is only the amount you invested — nothing more.", content:"التداول الفوري (Spot) يعني شراء العملة وامتلاكها فعلياً في محفظتك بسعرها الحالي، دون رافعة مالية أو مواعيد تسليم مستقبلية. يُعتبر أقل مخاطرة من الفيوتشر لأن أقصى خسارة ممكنة هي المبلغ المستثمر نفسه فقط، لا أكثر.", quiz:{q:"أقصى خسارة ممكنة في تداول السبوت (بدون رافعة) هي:",options:["أكبر من المبلغ المستثمر","المبلغ المستثمر فقط","لا حدود لها","صفر دائماً"],correct:1,q_en:"The max possible loss in spot trading (no leverage) is:",options_en:["More than the amount invested","Only the amount invested","Unlimited","Always zero"]}},
          {id:"a9", title:"التحليل", title_en:"Analysis", content_en:"Crypto analysis splits into two main types: technical analysis, which studies price movement, charts, and indicators to predict the next direction, and fundamental analysis, which studies a project's real value — its team, actual usage, and technical and economic developments around it.", content:"ينقسم التحليل في الكريبتو إلى نوعين رئيسيين: التحليل الفني الذي يدرس حركة السعر والمخططات والمؤشرات للتنبؤ بالاتجاه القادم، والتحليل الأساسي الذي يدرس قيمة المشروع الحقيقية: فريق العمل، الاستخدام الفعلي، والتطورات التقنية والاقتصادية المحيطة به.", image_url:"https://picsum.photos/seed/aw104/800/450", quiz:{q:"التحليل الأساسي في الكريبتو يهتم بدراسة:",options:["أشكال الشموع فقط","قيمة المشروع الحقيقية مثل الفريق والاستخدام","ألوان الرسم البياني","لا شيء محدد"],correct:1,q_en:"Fundamental analysis in crypto studies:",options_en:["Only candlestick shapes","A project's real value like its team and usage","Chart colors","Nothing specific"]}},
          {id:"a10", title:"منصات التداول الأكثر موثوقية", title_en:"The Most Trustworthy Trading Platforms", content_en:"When choosing a trading platform, look for: how long it's operated and its security track record, whether it holds an official license or regulation, its daily liquidity volume, and how clearly it states its policy for protecting customer funds. Don't rely on ads alone — check independent reviews and how it handled past crises.", content:"عند اختيار منصة تداول، ابحث عن: مدة عملها في السوق وسجلها الأمني، وجود ترخيص أو تنظيم رسمي، حجم السيولة اليومي، ووضوح سياسة حماية أموال العملاء. لا تعتمد فقط على الإعلانات، بل راجع تقييمات مستقلة وتاريخ المنصة في التعامل مع الأزمات السابقة.", quiz:{q:"عند اختيار منصة تداول موثوقة، يجب مراجعة:",options:["الإعلانات فقط","سجلها الأمني والترخيص والسيولة","لون الشعار","عدد المتابعين على انستغرام"],correct:1,q_en:"When choosing a trustworthy platform, check:",options_en:["Ads only","Its security record, license, and liquidity","The logo color","Instagram follower count"]}},
          {id:"a11", title:"معرفة المشاريع الاحتيالية والحقيقية", title_en:"Spotting Scam vs. Legitimate Projects", content_en:"Key red flags of scam projects: promises of guaranteed or huge quick returns, a fully anonymous team, no auditable source code, and psychological pressure to invest \"before it's too late.\" Serious projects are usually transparent about their team, regularly document technical progress, and never promise guaranteed profits.", content:"من أبرز علامات المشاريع الاحتيالية: وعود بعوائد مضمونة أو ضخمة بسرعة، فريق عمل مجهول الهوية بالكامل، عدم وجود كود مصدري قابل للتدقيق، وضغط نفسي لدفعك للاستثمار 'قبل فوات الأوان'. المشاريع الجادة عادة شفافة بفريقها، توثّق تقدمها التقني بانتظام، ولا تَعِد بأرباح مؤكدة.", quiz:{q:"من علامات المشروع الاحتيالي المحتمل:",options:["فريق عمل معروف وموثق","وعود بعوائد مضمونة وضخمة بسرعة","كود مصدري مفتوح للتدقيق","تقارير تقنية دورية"],correct:1,q_en:"A red flag of a potential scam project:",options_en:["A known, documented team","Promises of guaranteed huge quick returns","Open auditable source code","Regular technical reports"]}},
          {id:"a12", title:"أهم الشبكات المالية في العملات الرقمية", title_en:"Key Financial Networks in Crypto", content_en:"Networks like Bitcoin, Ethereum, and Layer 2 chains form the financial backbone of the crypto sector, alongside stablecoin networks linking the traditional economy to the digital world, and major DeFi protocols that now manage billions of dollars in liquidity without traditional banks.", content:"تشكل شبكات مثل بيتكوين وإيثريوم وشبكات الطبقة الثانية العمود الفقري المالي لقطاع الكريبتو، إضافة إلى شبكات العملات المستقرة التي تربط الاقتصاد التقليدي بالعالم الرقمي، وبروتوكولات DeFi الكبرى التي أصبحت تدير مليارات الدولارات من السيولة دون بنوك تقليدية.", quiz:{q:"من أهم الشبكات المالية في الكريبتو:",options:["شبكات الطعام فقط","بيتكوين وإيثريوم وبروتوكولات DeFi الكبرى","شبكات التلفزيون","لا شبكات مالية موجودة"],correct:1,q_en:"Among the key financial networks in crypto:",options_en:["Food delivery networks only","Bitcoin, Ethereum, and major DeFi protocols","TV broadcast networks","No financial networks exist"]}}
        ],
        exam: {
          pass: 60,
          questions: [
            {q:"آلية إثبات الحصة (Proof of Stake) اشتهرت باستخدامها من قِبل:", options:["البيتكوين منذ البداية","إيثريوم بعد التحديث عام 2022","الذهب الرقمي","لا تُستخدم في أي شبكة"], correct:1},
            {q:"الفرق الأساسي بين تداول السبوت والفيوتشر:", options:["لا فرق بينهما","السبوت امتلاك فعلي فوري، الفيوتشر مضاربة مستقبلية غالباً برافعة مالية","الفيوتشر أقل مخاطرة دائماً","السبوت غير قانوني"], correct:1},
            {q:"من علامات المشروع الاحتيالي المحتمل:", options:["فريق عمل معروف وموثق","وعود بعوائد مضمونة وضخمة بسرعة","كود مصدري مفتوح للتدقيق","تقارير تقنية دورية"], correct:1},
            {q:"بولكادوت (Polkadot) مصممة أساساً من أجل:", options:["استبدال إيثريوم فقط","ربط عدة بلوكتشينات مستقلة معاً","تخزين الصور فقط","التداول الفوري حصراً"], correct:1},
            {q:"التحليل الأساسي في الكريبتو يهتم بدراسة:", options:["أشكال الشموع فقط","قيمة المشروع الحقيقية مثل الفريق والاستخدام الفعلي","ألوان الرسم البياني","لا شيء محدد"], correct:1}
          ]
        }
      }
    ]
  }
,
  "crypto-bitcoin": {
    type: "flat",
    title: "ما هو الكريبتو والبيتكوين", title_en: "What Is Crypto & Bitcoin",
    lessons: [
      {id:"cb1", title:"ما هو الكريبتو", title_en:"What Is Crypto", content_en:"Crypto is an umbrella term for all encrypted digital currencies and assets built on blockchain technology. No government or central bank issues them, and their security relies on mathematical cryptography instead of trust in a middleman — a fundamental difference from traditional financial systems.", content:"الكريبتو مصطلح شامل يطلق على كل العملات والأصول الرقمية المشفّرة المبنية على تقنية البلوكتشين. لا تصدرها أي حكومة أو بنك مركزي، وتعتمد في أمانها على التشفير الرياضي بدل الثقة بجهة وسيطة، وهذا ما يميزها جذرياً عن الأنظمة المالية التقليدية.", quiz:{q:"مصطلح كريبتو يشمل:",options:["البيتكوين فقط","كل الأصول الرقمية المشفرة","نوعاً من الأسهم","عملة ورقية"],correct:1,q_en:"The term crypto covers:",options_en:["Bitcoin only","All encrypted digital assets","A type of stock","Paper currency"]}},
      {id:"cb2", title:"ما هو البيتكوين", title_en:"What Is Bitcoin", content_en:"Bitcoin is the first and most famous cryptocurrency in the world, launched in 2009 as a peer-to-peer electronic payment system needing no bank intermediary. Its supply is capped at 21 million coins, a scarcity that's a key reason many investors call it \"digital gold.\"", image_url:"https://picsum.photos/seed/aw105/800/450", content:"البيتكوين هو أول وأشهر عملة رقمية في العالم، أُطلقت عام 2009 كنظام دفع إلكتروني نظير-لنظير (Peer-to-Peer) لا يحتاج بنكاً وسيطاً. عرضها محدود بـ21 مليون عملة فقط، وهذا الندرة المبرمجة هي أحد أهم أسباب اعتبارها 'ذهباً رقمياً' من قِبل كثير من المستثمرين.", quiz:{q:"متى أُطلق البيتكوين؟",options:["1995","2009","2015","2020"],correct:1,q_en:"When was Bitcoin launched?",options_en:["1995","2009","2015","2020"]}},
      {id:"cb3", title:"كيف يعمل البيتكوين", title_en:"How Bitcoin Works", content_en:"When you send Bitcoin, the transaction broadcasts to thousands of machines worldwide (nodes) that verify it, then miners bundle it into a new \"block\" added permanently to the chain of prior blocks. This decentralized process replaces the bank's role in verifying a transaction.", video_url:"https://developer.mozilla.org/shared-assets/videos/flower.mp4", content:"عندما تُرسِل بيتكوين، تُبث المعاملة لآلاف الأجهزة حول العالم (العُقَد) التي تتحقق من صحتها، ثم يجمّعها المعدّنون في 'كتلة' جديدة تُضاف لسلسلة الكتل السابقة بشكل دائم لا يمكن التراجع عنه. هذه العملية اللامركزية تحل محل دور البنك في التحقق من صحة العملية.", quiz:{q:"من يتحقق من صحة معاملات البيتكوين؟",options:["بنك مركزي واحد","آلاف العُقد الموزعة","شركة واحدة","لا أحد"],correct:1,q_en:"Who verifies Bitcoin transactions?",options_en:["A single central bank","Thousands of distributed nodes","One company","No one"]}},
      {id:"cb4", title:"من هو مؤسس البيتكوين", title_en:"Who Founded Bitcoin", content_en:"Bitcoin launched under the pseudonym \"Satoshi Nakamoto,\" and to this day it's not confirmed whether that's one person or a group, nor their real identity. Satoshi disappeared from public view in 2011, leaving the project in the hands of the decentralized developer community that runs it today.", content:"أُطلق البيتكوين تحت اسم مستعار 'ساتوشي ناكاموتو'، وحتى اليوم لا يُعرف بشكل مؤكد هل هو شخص واحد أو مجموعة أشخاص، ولا هويته الحقيقية. اختفى ساتوشي من الساحة العلنية عام 2011 تاركاً المشروع بين يدي مجتمع المطورين اللامركزي الذي يديره حتى الآن.", quiz:{q:"من هو مؤسس البيتكوين المعروف؟",options:["إيلون ماسك","ساتوشي ناكاموتو (اسم مستعار)","فيتاليك بوتيرين","لا يوجد مؤسس"],correct:1,q_en:"Who is Bitcoin's known founder?",options_en:["Elon Musk","Satoshi Nakamoto (pseudonym)","Vitalik Buterin","There is no founder"]}},
      {id:"cb5", title:"تعدين البيتكوين", title_en:"Bitcoin Mining", content_en:"Mining is the process by which new transactions get added to the Bitcoin chain: powerful machines worldwide compete to solve a complex calculation, and the winner adds the new block and earns a reward of freshly-issued bitcoin. This mechanism is called \"Proof of Work.\"", content:"التعدين هو العملية التي تُضاف بها معاملات جديدة لسلسلة البيتكوين، حيث تتنافس أجهزة قوية حول العالم على حل مسألة حسابية معقدة، والفائز يضيف الكتلة الجديدة ويحصل على مكافأة بعملات بيتكوين حديثة الإصدار. هذه الآلية تسمى 'إثبات العمل' (Proof of Work).", quiz:{q:"آلية تعدين البيتكوين تسمى:",options:["إثبات الحصة","إثبات العمل","إثبات الهوية","لا اسم لها"],correct:1,q_en:"Bitcoin's mining mechanism is called:",options_en:["Proof of Stake","Proof of Work","Proof of Identity","It has no name"]}},
      {id:"cb6", title:"من يتحكم بالبيتكوين", title_en:"Who Controls Bitcoin", content_en:"No single entity controls the Bitcoin network; the rules are defined by open-source code, and any major change needs agreement from a majority of miners, nodes, and users. This distribution is what makes the network resistant to censorship or shutdown by any one government or company.", content:"لا توجد جهة واحدة تتحكم بشبكة البيتكوين؛ فالقواعد يحددها الكود مفتوح المصدر، وأي تعديل جوهري يحتاج موافقة غالبية المعدّنين والعُقَد والمستخدمين. هذا التوزع هو ما يجعل الشبكة مقاومة للرقابة أو التوقف من قبل أي حكومة أو شركة بمفردها.", quiz:{q:"من يتحكم بشبكة البيتكوين؟",options:["حكومة واحدة","لا جهة مركزية واحدة","شركة واحدة فقط","بنك دولي"],correct:1,q_en:"Who controls the Bitcoin network?",options_en:["A single government","No single central entity","Just one company","An international bank"]}},
      {id:"cb7", title:"الخصوصية في البيتكوين", title_en:"Privacy in Bitcoin", content_en:"Bitcoin transactions are fully transparent and public on the blockchain, but they're \"pseudonymous\" rather than truly anonymous: addresses don't carry your name directly, but linking your address to your real identity (like registering on an exchange) reveals your entire financial activity to anyone analyzing the chain.", content:"معاملات البيتكوين شفافة وعلنية بالكامل على البلوكتشين، لكنها 'شبه مجهولة' وليست مجهولة تماماً: العناوين لا تحمل اسمك مباشرة، لكن أي ربط بين عنوانك وهويتك الحقيقية (كالتسجيل بمنصة تداول) يكشف نشاطك المالي بالكامل لمن يحلل السلسلة.", quiz:{q:"معاملات البيتكوين تُعتبر:",options:["مجهولة تماماً","شبه مجهولة (pseudonymous)","سرية بالكامل عن الشبكة","غير مسجلة إطلاقاً"],correct:1,q_en:"Bitcoin transactions are considered:",options_en:["Fully anonymous","Pseudonymous","Completely hidden from the network","Not recorded at all"]}},
      {id:"cb8", title:"الأمان في البيتكوين", title_en:"Security in Bitcoin", content_en:"Bitcoin's network security comes from the sheer scale of mining power involved, making tampering with the historical record too costly to be worthwhile. The security of your personal funds, though, depends on you: protecting your private key is the one real line of defense.", content:"أمان شبكة البيتكوين يعتمد على ضخامة قوة التعدين المشاركة فيها، ما يجعل التلاعب بالسجل التاريخي مكلفاً بشكل يفوق أي فائدة محتملة. أما أمان أموالك الشخصية فيعتمد عليك أنت: حماية مفتاحك الخاص هي خط الدفاع الحقيقي الوحيد.", quiz:{q:"أكبر خط دفاع لأموالك الشخصية في البيتكوين هو:",options:["كلمة سر بريدك الإلكتروني","حماية مفتاحك الخاص","اسم المستخدم","لا شيء يهم"],correct:1,q_en:"The biggest defense for your personal Bitcoin funds is:",options_en:["Your email password","Protecting your private key","Your username","Nothing matters"]}}
    ]
  },

  "wallets": {
    type: "flat",
    title: "المحافظ الرقمية", title_en: "Digital Wallets",
    lessons: [
      {id:"w1", title:"ما هي المحفظة الرقمية؟", title_en:"What Is a Digital Wallet?", content_en:"A digital wallet isn't a physical place that stores coins — it's a tool that holds your public and private keys, proving your ownership of assets recorded on the blockchain and letting you sign and send transactions securely.", content:"المحفظة الرقمية ليست مكاناً فعلياً لتخزين العملات، بل أداة تحفظ مفاتيحك الخاصة والعامة التي تثبت ملكيتك للأصول المسجّلة على البلوكتشين وتتيح لك توقيع المعاملات وإرسالها بأمان.", quiz:{q:"المحفظة الرقمية تحفظ بشكل أساسي:",options:["العملات فعلياً بداخلها","مفاتيحك العامة والخاصة","صوراً شخصية","كلمة سر البريد"],correct:1,q_en:"A digital wallet primarily stores:",options_en:["The actual coins inside it","Your public and private keys","Personal photos","Your email password"]}},
      {id:"w2", title:"لماذا نحتاج محفظة؟", title_en:"Why Do We Need a Wallet?", content_en:"Without a wallet, you can't receive, send, or even prove ownership of any cryptocurrency. It's your \"financial identity\" in the decentralized world, replacing the traditional bank account with no intermediary managing it.", content:"بدون محفظة، لا يمكنك استلام أو إرسال أو حتى إثبات ملكية أي عملة رقمية، فهي بمثابة 'هويتك المالية' في العالم اللامركزي التي تحل محل الحساب البنكي التقليدي دون وسيط يديره.", quiz:{q:"بدون محفظة رقمية، لا يمكنك:",options:["مشاهدة الأسعار","إثبات ملكية أو إرسال عملات","قراءة الأخبار","تصفح الإنترنت"],correct:1,q_en:"Without a digital wallet, you can't:",options_en:["View prices","Prove ownership or send coins","Read the news","Browse the internet"]}},
      {id:"w3", title:"كيف تعمل المحفظة؟", title_en:"How a Wallet Works", content_en:"A wallet generates a pair of keys: a public one you share to receive funds, and a private one you keep secret to sign any outgoing transaction. Your digital signature proves to the network that you truly own the funds, without any traditional password.", image_url:"https://picsum.photos/seed/aw106/800/450", content:"تولّد المحفظة زوجاً من المفاتيح: عاماً تشاركه لاستقبال الأموال، وخاصاً تحتفظ به سرياً لتوقيع أي معاملة صادرة. توقيعك الرقمي يثبت للشبكة أنك فعلاً صاحب الأموال دون كشف كلمة سر تقليدية.", quiz:{q:"توقيعك الرقمي في المحفظة يثبت:",options:["اسمك الحقيقي","ملكيتك للأموال دون كلمة سر تقليدية","عمرك","جنسيتك"],correct:1,q_en:"Your digital signature in a wallet proves:",options_en:["Your real name","Fund ownership without a traditional password","Your age","Your nationality"]}},
      {id:"w4", title:"أنواع المحافظ", title_en:"Types of Wallets", content_en:"Wallets split into: hot wallets (apps or websites connected to the internet, easy to use but more exposed to hacking) and cold wallets (physical or paper, offline devices, slower but much safer for storing large amounts long-term).", content:"تنقسم المحافظ إلى: محافظ ساخنة (تطبيقات أو مواقع متصلة بالإنترنت، سهلة الاستخدام لكن أكثر عرضة للاختراق)، ومحافظ باردة (أجهزة فيزيائية أو ورقية غير متصلة، أبطأ لكن أكثر أماناً لتخزين المبالغ الكبيرة على المدى الطويل).", quiz:{q:"المحفظة الباردة (Cold Wallet) هي:",options:["دائماً متصلة بالإنترنت","جهاز أو وسيلة غير متصلة بالإنترنت","تطبيق موبايل فقط","غير آمنة إطلاقاً"],correct:1,q_en:"A cold wallet is:",options_en:["Always connected to the internet","An offline device or method","A mobile app only","Never secure"]}},
      {id:"w5", title:"إنشاء محفظة", title_en:"Creating a Wallet", content_en:"When you create a new wallet, you get a 12- or 24-word \"recovery phrase\" — the only backup for all your funds. Write it on paper and store it somewhere physically safe, and never type it into any website or app that suddenly asks for it.", content:"عند إنشاء محفظة جديدة، تحصل على 'عبارة استرداد' (Seed Phrase) من 12 أو 24 كلمة — هذه هي النسخة الاحتياطية الوحيدة لكل أموالك. اكتبها على ورق واحفظها في مكان آمن فعلياً، ولا تُدخلها أبداً في أي موقع أو تطبيق يطلبها بشكل مفاجئ.", quiz:{q:"عبارة الاسترداد (Seed Phrase) يجب أن:",options:["تُشارك مع أي موقع يطلبها","تُحفظ ورقياً في مكان آمن","تُنشر على تويتر","تُحفظ في ملاحظات الهاتف"],correct:1,q_en:"A recovery (seed) phrase should be:",options_en:["Shared with any site that asks","Stored on paper somewhere safe","Posted on Twitter","Saved in phone notes"]}},
      {id:"w6", title:"من يتحكم بالمحفظة؟", title_en:"Who Controls the Wallet?", content_en:"In \"non-custodial\" wallets, you alone hold the private key and full control. Platform wallets (custodial), like exchange wallets, actually hold your keys for you — hence the saying: \"not your keys, not your coins.\"", content:"في المحافظ 'غير الحافظة' (Non-Custodial) أنت وحدك تملك المفتاح الخاص والتحكم الكامل. أما محافظ المنصات (Custodial) مثل منصات التداول، فهي من تحتفظ بمفاتيحك فعلياً؛ لهذا يُقال 'ما ليس مفتاحك، ليس عملتك'.", quiz:{q:"في المحافظ غير الحافظة (Non-Custodial)، من يملك المفتاح الخاص؟",options:["المنصة","أنت وحدك","الحكومة","لا أحد"],correct:1,q_en:"In a non-custodial wallet, who owns the private key?",options_en:["The platform","You alone","The government","No one"]}},
      {id:"w7", title:"الخصوصية في المحافظ", title_en:"Privacy in Wallets", content_en:"Your wallet address doesn't carry your name, but every transaction tied to it stays recorded publicly on the blockchain forever. Using a fresh address for each important transaction reduces how easily others can link your financial activity to your identity.", content:"عنوان محفظتك لا يحمل اسمك، لكن كل معاملة مرتبطة به تبقى مسجّلة وعلنية للأبد على البلوكتشين. استخدام عنوان جديد لكل معاملة مهمة يقلل من قدرة الآخرين على ربط نشاطك المالي بهويتك.", quiz:{q:"لتقليل ربط نشاطك المالي بهويتك، يُنصح باستخدام:",options:["نفس العنوان دائماً","عنوان جديد لكل معاملة مهمة","اسمك الحقيقي كعنوان","لا حاجة لأي إجراء"],correct:1,q_en:"To reduce linking your activity to your identity, it's wise to use:",options_en:["The same address always","A fresh address for each important transaction","Your real name as the address","No precaution is needed"]}},
      {id:"w8", title:"أمان المحافظ", title_en:"Wallet Security", content_en:"The biggest threat to your wallet usually isn't a network hack — it's accidentally sharing your recovery phrase with a phishing site or storing it insecurely online. Enable two-factor authentication wherever possible, and use a cold wallet for any amount you don't need to move daily.", content:"أكبر تهديد لمحفظتك ليس اختراق الشبكة، بل مشاركة عبارة الاسترداد بالخطأ مع موقع احتيالي أو تخزينها رقمياً بشكل غير آمن. فعّل التحقق بخطوتين حيثما أمكن، واستخدم محفظة باردة لأي مبلغ لا تحتاج تحريكه يومياً.", quiz:{q:"أكبر تهديد شائع لأمان المحفظة هو:",options:["اختراق الشبكة نفسها","مشاركة عبارة الاسترداد بالخطأ","تحديث التطبيق","لا شيء"],correct:1,q_en:"The most common threat to wallet security is:",options_en:["Hacking the network itself","Accidentally sharing the recovery phrase","Updating the app","Nothing"]}}
    ]
  },

  "trading": {
    type: "flat",
    title: "التداول", title_en: "Trading",
    lessons: [
      {id:"tr1", title:"ما هو التداول؟", title_en:"What Is Trading?", content_en:"Trading means buying and selling digital assets aiming to profit from short-to-medium-term price swings, unlike long-term investing which holds for years while ignoring daily volatility.", content:"التداول هو شراء وبيع الأصول الرقمية بهدف الربح من فروقات الأسعار على المدى القصير أو المتوسط، ويختلف عن الاستثمار طويل الأمد الذي يعتمد على الاحتفاظ لسنوات متجاهلاً التقلبات اليومية.", quiz:{q:"التداول يهدف بشكل أساسي إلى:",options:["الاحتفاظ لعقود دون بيع","الربح من فروق الأسعار قصيرة/متوسطة المدى","تجنب أي بيع أو شراء","لا هدف محدد"],correct:1,q_en:"Trading is mainly aimed at:",options_en:["Holding for decades without selling","Profiting from short/medium-term price swings","Avoiding any buying or selling","No specific goal"]}},
      {id:"tr2", title:"لماذا يتداول الناس؟", title_en:"Why Do People Trade?", content_en:"People trade to profit from fast market swings, to rebalance their investment portfolio, or to capture short-term opportunities driven by news or events affecting a particular coin's price.", content:"يتداول الناس لتحقيق أرباح من تقلبات السوق السريعة، أو لإعادة توازن محفظتهم الاستثمارية، أو للاستفادة من فرص قصيرة الأمد ناتجة عن أخبار أو أحداث تؤثر على سعر عملة معينة.", quiz:{q:"من أسباب تداول الناس:",options:["الملل فقط","تحقيق أرباح من التقلبات وإعادة توازن المحفظة","تجنب الأرباح","لا سبب حقيقي"],correct:1,q_en:"A reason people trade is:",options_en:["Boredom only","Profiting from swings and portfolio rebalancing","Avoiding profit","No real reason"]}},
      {id:"tr3", title:"كيف يعمل التداول؟", title_en:"How Trading Works", content_en:"Trading runs on supply and demand: when demand for a coin rises relative to its available supply, its price rises, and vice versa. Traders use charts and indicators to try to predict the next price move.", video_url:"https://developer.mozilla.org/shared-assets/videos/flower.mp4", content:"يعتمد التداول على مبدأ العرض والطلب: حين يزيد الطلب على عملة عن المعروض منها يرتفع سعرها، والعكس صحيح. يستخدم المتداولون الرسوم البيانية والمؤشرات لمحاولة التنبؤ بحركة السعر القادمة.", quiz:{q:"سعر العملة يرتفع عادة عندما:",options:["يزيد الطلب عن العرض","يزيد العرض فقط دون طلب","لا علاقة للعرض والطلب","تتوقف الشبكة"],correct:0,q_en:"A coin's price usually rises when:",options_en:["Demand exceeds supply","Only supply increases with no demand","Supply and demand are irrelevant","The network stops"]}},
      {id:"tr4", title:"منصات التداول", title_en:"Trading Platforms", content_en:"Trading platforms, whether centralized or decentralized, let you execute buy and sell orders, and provide tools like charts, order books, and multiple order types to help you execute your strategy precisely.", content:"تتيح منصات التداول (سواء مركزية أو لامركزية) تنفيذ صفقات الشراء والبيع، وتوفر أدوات مثل الرسوم البيانية، دفاتر الأوامر، وأنواع أوامر متعددة لمساعدتك على تنفيذ استراتيجيتك بدقة.", quiz:{q:"منصات التداول توفر عادة:",options:["لا أدوات إطلاقاً","رسوماً بيانية ودفاتر أوامر وأنواع أوامر متعددة","خدمة بريد فقط","لا علاقة لها بالتنفيذ"],correct:1,q_en:"Trading platforms typically provide:",options_en:["No tools at all","Charts, order books, and multiple order types","Only an email service","Nothing related to execution"]}},
      {id:"tr5", title:"أوامر البيع والشراء", title_en:"Buy and Sell Orders", content_en:"The most common order types: market orders (instant execution at current price) and limit orders, which only execute once the price reaches a level you set in advance, giving you tighter control over your entry or exit price.", content:"أشهر أنواع الأوامر: أمر السوق (تنفيذ فوري بالسعر الحالي)، وأمر الحد (Limit Order) الذي ينفَّذ فقط عند وصول السعر لمستوى تحدده أنت مسبقاً، ما يمنحك تحكماً أدق في سعر الدخول أو الخروج.", quiz:{q:"أمر الحد (Limit Order) ينفَّذ:",options:["فوراً بأي سعر","فقط عند وصول السعر لمستوى تحدده أنت","بعد شهر دائماً","عشوائياً"],correct:1,q_en:"A limit order executes:",options_en:["Instantly at any price","Only when price reaches your set level","Always after a month","Randomly"]}},
      {id:"tr6", title:"من يتحكم بالسوق؟", title_en:"Who Controls the Market?", content_en:"No single entity fully controls the crypto market, but large holders (\"whales\"), major exchanges, and regulatory news can move it noticeably, especially in lower-liquidity coins.", content:"لا جهة واحدة تتحكم بسوق الكريبتو بالكامل، لكن كبار الحائزين ('الحيتان') ومنصات التداول الكبرى والأخبار التنظيمية يمكن أن تحرك السوق بشكل ملحوظ، خصوصاً في العملات ذات السيولة المنخفضة.", quiz:{q:"من يمكنه التأثير الملحوظ على السوق؟",options:["لا أحد إطلاقاً","كبار الحائزين (الحيتان) والمنصات الكبرى","الطقس فقط","لا علاقة بأي طرف"],correct:1,q_en:"Who can noticeably move the market?",options_en:["No one at all","Large holders (\"whales\") and major exchanges","The weather only","No party has any effect"]}},
      {id:"tr7", title:"مخاطر التداول", title_en:"Trading Risks", content_en:"Trading carries real risk of losing capital, especially with leverage, which multiplies losses just as it multiplies gains. Never trade with money you can't afford to lose, and don't rely on unverified \"tips.\"", content:"التداول يحمل مخاطرة حقيقية بخسارة رأس المال، خاصة مع استخدام الرافعة المالية التي تضاعف الخسائر كما تضاعف الأرباح. لا تتداول أبداً بأموال لا يمكنك تحمل خسارتها، ولا تعتمد على 'نصائح' غير موثقة.", quiz:{q:"الرافعة المالية في التداول:",options:["تلغي المخاطر كلياً","تضاعف الأرباح والخسائر معاً","مضمونة الربح","غير موجودة في الكريبتو"],correct:1,q_en:"Leverage in trading:",options_en:["Eliminates all risk","Multiplies both gains and losses","Guarantees profit","Doesn't exist in crypto"]}},
      {id:"tr8", title:"أمان التداول", title_en:"Trading Security", content_en:"Enable two-factor authentication on your platform account, use strong unique passwords, and watch out for phishing links impersonating well-known platforms. Never share your login details with anyone claiming to be \"support\" via direct message.", content:"فعّل التحقق بخطوتين على حساب منصتك، استخدم كلمات مرور فريدة وقوية، واحذر من روابط تصيّد تنتحل شكل منصات معروفة. لا تشارك بيانات دخولك مع أي جهة تدّعي أنها 'دعم فني' عبر رسالة مباشرة.", quiz:{q:"لحماية حساب التداول، يُنصح بـ:",options:["مشاركة كلمة السر مع الدعم الفني عبر رسالة","تفعيل التحقق بخطوتين","تجاهل الروابط المشبوهة دون فحص","استخدام نفس كلمة السر بكل مكان"],correct:1,q_en:"To protect your trading account, it's wise to:",options_en:["Share your password with \"support\" via message","Enable two-factor authentication","Ignore suspicious links without checking","Reuse the same password everywhere"]}}
    ]
  },

  "blockchain": {
    type: "flat",
    title: "ما هو البلوكشين؟", title_en: "What Is Blockchain?",
    lessons: [
      {id:"bc1", title:"لماذا تم إنشاء البلوكشين؟", title_en:"Why Blockchain Was Created", content_en:"Blockchain was designed to solve the \"double-spending\" problem in digital money without needing a trusted central authority to verify every transaction, through a distributed ledger that thousands of independent participants agree on.", content:"صُمم البلوكتشين لحل مشكلة 'الإنفاق المزدوج' في النقود الرقمية دون الحاجة لجهة مركزية موثوقة تتحقق من كل معاملة، عبر سجل موزّع يتفق عليه آلاف المشاركين بشكل مستقل.", quiz:{q:"البلوكتشين صُمم أساساً لحل مشكلة:",options:["بطء الإنترنت","الإنفاق المزدوج للنقود الرقمية","ارتفاع الضرائب","نقص الكهرباء"],correct:1,q_en:"Blockchain was primarily designed to solve:",options_en:["Slow internet","Double-spending of digital money","High taxes","Power shortages"]}},
      {id:"bc2", title:"كيف يعمل البلوكشين؟", title_en:"How Blockchain Works", content_en:"Transactions are grouped into \"blocks,\" and each new block links mathematically to the one before it via cryptography, making it impossible to alter an old block without the network instantly noticing, since every distributed copy holds the full record.", image_url:"https://picsum.photos/seed/aw107/800/450", content:"تُجمَّع المعاملات في 'كتل'، وكل كتلة جديدة ترتبط رياضياً بالكتلة التي سبقتها عبر تشفير، بحيث يستحيل تعديل كتلة قديمة دون أن ينكشف الأمر فوراً لبقية الشبكة، لأن كل نسخة موزّعة تحتفظ بالسجل كاملاً.", quiz:{q:"كل كتلة جديدة في البلوكتشين ترتبط بالسابقة عبر:",options:["رابط عادي","تشفير رياضي","بريد إلكتروني","لا رابط بينها"],correct:1,q_en:"Each new block links to the previous one via:",options_en:["A plain link","Cryptographic math","Email","No link at all"]}},
      {id:"bc3", title:"من اخترع البلوكشين؟", title_en:"Who Invented Blockchain", content_en:"Ideas resembling blockchain first appeared in research papers from the early 1990s for securing document timestamps, but Satoshi Nakamoto built the first successful practical implementation in the 2008 Bitcoin whitepaper.", content:"ظهرت أفكار أولية شبيهة بالبلوكتشين في أوراق بحثية من مطلع التسعينيات لتأمين الطوابع الزمنية للمستندات، لكن ساتوشي ناكاموتو هو من طوّر أول تطبيق عملي وناجح لها ضمن ورقة البيتكوين البحثية عام 2008.", quiz:{q:"من طوّر أول تطبيق عملي وناجح للبلوكتشين؟",options:["فيتاليك بوتيرين","ساتوشي ناكاموتو","بنك مركزي","شركة جوجل"],correct:1,q_en:"Who developed the first successful practical blockchain application?",options_en:["Vitalik Buterin","Satoshi Nakamoto","A central bank","Google"]}},
      {id:"bc4", title:"العقد (Nodes) والشبكة", title_en:"Nodes and the Network", content_en:"A node is any computer participating in a blockchain network by holding a copy of the ledger and verifying new transactions. The more nodes distributed globally, the more decentralized the network becomes and the harder it is to tamper with or shut down.", content:"العقدة (Node) هي أي جهاز حاسوبي يشارك في شبكة البلوكتشين بالاحتفاظ بنسخة من السجل والتحقق من صحة المعاملات الجديدة. كلما زاد عدد العُقد الموزعة جغرافياً، زادت لامركزية الشبكة وصعُب التلاعب بها أو إيقافها.", quiz:{q:"العقدة (Node) في شبكة البلوكتشين هي:",options:["جهاز يحتفظ بنسخة من السجل ويتحقق من المعاملات","بطاقة ائتمان","اسم مستخدم","نوع من العملات"],correct:0,q_en:"A node in a blockchain network is:",options_en:["A device holding a copy of the ledger and verifying transactions","A credit card","A username","A type of coin"]}},
      {id:"bc5", title:"من يتحكم بالبلوكشين؟", title_en:"Who Controls Blockchain?", content_en:"Public blockchains aren't controlled by any single central authority; major decisions (like rule updates) need broad agreement among developers, miners/validators, and users, and any party that rejects an update can simply keep running the old version.", content:"شبكات البلوكتشين العامة لا تخضع لجهة مركزية واحدة؛ القرارات الكبرى (مثل تحديث قواعد الشبكة) تحتاج توافقاً واسعاً بين المطورين والمعدّنين/المدققين والمستخدمين، وأي طرف يرفض التحديث يمكنه الاستمرار على النسخة القديمة.", quiz:{q:"قرارات تحديث شبكة بلوكتشين عامة تحتاج:",options:["موافقة شركة واحدة فقط","توافقاً واسعاً بين المطورين والمشاركين","لا شيء، تتم تلقائياً","موافقة حكومة واحدة"],correct:1,q_en:"Major updates to a public blockchain need:",options_en:["Approval from one company only","Broad consensus among developers and participants","Nothing, happens automatically","Approval from one government"]}},
      {id:"bc6", title:"الخصوصية في البلوكشين", title_en:"Privacy in Blockchain", content_en:"A public blockchain is a transparent ledger anyone can view, but the identities behind addresses aren't directly exposed. Some newer networks have developed advanced cryptographic techniques to hide transaction details while still allowing them to be verified.", content:"البلوكتشين العام سجل شفاف يراه الجميع، لكن الهويات خلف العناوين غير مكشوفة مباشرة. بعض الشبكات الحديثة طوّرت تقنيات تشفير متقدمة لإخفاء تفاصيل المعاملة نفسها مع الحفاظ على إمكانية التحقق منها.", quiz:{q:"معاملات البلوكتشين العام تُعتبر:",options:["سرية تماماً ولا يراها أحد","علنية وشفافة لكن الهويات غير مكشوفة مباشرة","محذوفة تلقائياً بعد يوم","متاحة فقط للحكومات"],correct:1,q_en:"Public blockchain transactions are:",options_en:["Fully private and hidden","Public and transparent, but identities aren't directly revealed","Auto-deleted after a day","Only visible to governments"]}},
      {id:"bc7", title:"الأمان في البلوكشين", title_en:"Security in Blockchain", content_en:"Blockchain security comes from its distribution: changing an old record requires controlling an overwhelming majority of the network's power at once — practically impossible in large, established networks like Bitcoin and Ethereum.", content:"أمان البلوكتشين يأتي من توزّعه: لتغيير سجل قديم يجب التحكم بغالبية ساحقة من قوة الشبكة في نفس الوقت، وهو أمر شبه مستحيل عملياً في الشبكات الكبيرة والراسخة مثل بيتكوين وإيثريوم.", quiz:{q:"لتغيير سجل قديم في بلوكتشين كبير، يحتاج المهاجم:",options:["كلمة مرور واحدة","التحكم بغالبية ساحقة من قوة الشبكة دفعة واحدة","إذن من مستخدم واحد","لا شيء تقريباً"],correct:1,q_en:"To alter old records on a large blockchain, an attacker needs:",options_en:["One password","Overwhelming control of network power all at once","Permission from one user","Almost nothing"]}}
    ]
  },

  "ethereum": {
    type: "flat",
    title: "الإيثريوم والعقود الذكية", title_en: "Ethereum & Smart Contracts",
    lessons: [
      {id:"eth1", title:"ما هو الإيثريوم", title_en:"What Is Ethereum", content_en:"Ethereum is a blockchain network that goes beyond being just a payment coin — it's a decentralized \"world computer\" that lets any developer build and run full applications on top of it, with no central server owned by anyone.", content:"إيثريوم شبكة بلوكتشين تتجاوز فكرة كونها عملة دفع فقط، فهي 'حاسوب عالمي' لامركزي يتيح لأي مطور بناء وتشغيل تطبيقات كاملة فوقها دون خادم مركزي يملكه أحد.", quiz:{q:"إيثريوم يوصف غالباً بأنه:",options:["عملة دفع فقط بلا مزايا أخرى","حاسوب عالمي لامركزي لتشغيل تطبيقات","بنك مركزي رقمي","شبكة اجتماعية"],correct:1,q_en:"Ethereum is often described as:",options_en:["Just a payment coin with nothing else","A decentralized world computer for running apps","A digital central bank","A social network"]}},
      {id:"eth2", title:"لماذا تم إنشاء الإيثريوم؟", title_en:"Why Ethereum Was Created", content_en:"Ethereum was created because Bitcoin was primarily designed as a payment system with limited programmability, while Ethereum's founders wanted a flexible platform that could run any kind of decentralized application with open-ended programming logic.", content:"أُنشئ إيثريوم لأن بيتكوين صُمم أساساً كنظام دفع محدود الإمكانيات البرمجية، بينما أراد مؤسسو إيثريوم منصة مرنة تتيح بناء أي نوع من التطبيقات اللامركزية بمنطق برمجي حر.", quiz:{q:"السبب الرئيسي لإنشاء إيثريوم كان:",options:["نسخ البيتكوين حرفياً","حاجة لمنصة مرنة تدعم أي تطبيق لامركزي","استبدال الدولار فقط","تخزين الصور"],correct:1,q_en:"The main reason Ethereum was created:",options_en:["To copy Bitcoin exactly","Need for a flexible platform supporting any decentralized app","To replace the dollar only","To store photos"]}},
      {id:"eth3", title:"كيف يعمل الإيثريوم؟", title_en:"How Ethereum Works", content_en:"Ethereum runs a distributed \"virtual machine\" (the EVM) across every node in the network, executing smart contracts identically on each machine, with the cost of each operation paid via fees called \"Gas.\"", video_url:"https://developer.mozilla.org/shared-assets/videos/flower.mp4", content:"يشغّل إيثريوم 'آلة افتراضية' (EVM) موزعة على كل عُقد الشبكة، تُنفَّذ فيها العقود الذكية بشكل متطابق على كل جهاز، وتُدفع تكلفة كل عملية عبر رسوم تسمى 'الغاز' (Gas).", quiz:{q:"رسوم تنفيذ العمليات على إيثريوم تسمى:",options:["Gas","Coin","Fee-tax","Bit"],correct:0,q_en:"The fee for executing operations on Ethereum is called:",options_en:["Gas","Coin","Fee-tax","Bit"]}},
      {id:"eth4", title:"من هو مؤسس الإيثريوم؟", title_en:"Who Founded Ethereum", content_en:"Vitalik Buterin proposed the idea of Ethereum in 2013 at age nineteen, alongside several co-founders, and the network officially launched in 2015 to become the second-largest blockchain network in the world.", content:"أطلق فيتاليك بوتيرين فكرة إيثريوم عام 2013 وهو في سن التاسعة عشرة، بمشاركة عدد من المؤسسين المشاركين، وأُطلقت الشبكة فعلياً عام 2015 لتصبح ثاني أكبر شبكة بلوكتشين في العالم.", quiz:{q:"من أطلق فكرة إيثريوم؟",options:["ساتوشي ناكاموتو","فيتاليك بوتيرين","إيلون ماسك","بنك مركزي"],correct:1,q_en:"Who launched the idea of Ethereum?",options_en:["Satoshi Nakamoto","Vitalik Buterin","Elon Musk","A central bank"]}},
      {id:"eth5", title:"ما هي العقود الذكية؟", title_en:"What Are Smart Contracts?", content_en:"A smart contract is a program stored on the blockchain that executes automatically once predefined conditions are met, with no human intermediary, and in a way that's impossible for any single party to alter or stop after it's published.", content:"العقد الذكي برنامج مخزّن على البلوكتشين يُنفَّذ تلقائياً عند تحقق شروط برمجية محددة مسبقاً، دون تدخل بشري أو وسيط، وبشكل يستحيل تغييره أو إيقافه من طرف واحد بعد نشره.", quiz:{q:"العقد الذكي هو:",options:["اتفاق ورقي موقّع يدوياً","برنامج على البلوكتشين يُنفَّذ تلقائياً عند تحقق شروط معينة","نوع من المحافظ الباردة","اسم مستخدم على منصة"],correct:1,q_en:"A smart contract is:",options_en:["A hand-signed paper agreement","A program on the blockchain that executes automatically when conditions are met","A type of cold wallet","A platform username"]}},
      {id:"eth6", title:"كيف تعمل العقود الذكية؟", title_en:"How Smart Contracts Work", content_en:"A developer writes the contract's terms in a specialized programming language (usually Solidity), then deploys it on the network. When any user meets the required conditions (like sending a certain amount), the contract automatically executes the programmed outcome, fully transparently.", content:"يكتب المطور شروط العقد بلغة برمجة مخصصة (Solidity غالباً)، ثم يُنشر على الشبكة. عندما يستوفي أي مستخدم الشروط المطلوبة (كإرسال مبلغ معين)، ينفّذ العقد النتيجة المبرمجة تلقائياً وبشفافية كاملة.", quiz:{q:"لغة البرمجة الأشهر لكتابة العقود الذكية على إيثريوم هي:",options:["Python","Solidity","HTML","Excel"],correct:1,q_en:"The most common language for writing Ethereum smart contracts is:",options_en:["Python","Solidity","HTML","Excel"]}},
      {id:"eth7", title:"التطبيقات اللامركزية DApps", title_en:"Decentralized Applications (DApps)", content_en:"A DApp is an application built on top of smart contracts instead of a company's central server, meaning no single party can shut it down or tamper with its data or logic — spanning DeFi, gaming, and digital marketplaces.", content:"DApp هو تطبيق مبني فوق عقود ذكية بدل خادم شركة مركزية، ما يعني أن بياناته ومنطقه لا يمكن لأي جهة واحدة إيقافها أو التلاعب بها، وتشمل تطبيقات التمويل اللامركزي، الألعاب، والأسواق الرقمية.", quiz:{q:"تطبيق DApp يُبنى فوق:",options:["خادم شركة مركزية","عقود ذكية على البلوكتشين","جهاز مستخدم واحد فقط","لا شيء"],correct:1,q_en:"A DApp is built on top of:",options_en:["A centralized company server","Smart contracts on the blockchain","Just one user's device","Nothing"]}},
      {id:"eth8", title:"من يتحكم بالإيثريوم؟", title_en:"Who Controls Ethereum?", content_en:"Like Bitcoin, no central entity owns Ethereum; major upgrades require broad community agreement among developers and the validators who've secured the network since its shift to Proof of Stake.", content:"مثل بيتكوين، لا جهة مركزية تملك إيثريوم؛ التحديثات الكبرى تحتاج توافقاً مجتمعياً واسعاً بين المطورين والمدققين (Validators) الذين يؤمّنون الشبكة منذ تحوّلها لآلية إثبات الحصة.", quiz:{q:"تحديثات إيثريوم الكبرى تحتاج:",options:["موافقة شركة واحدة","توافقاً مجتمعياً واسعاً بين المطورين والمدققين","لا شيء، تلقائية بالكامل","موافقة بنك"],correct:1,q_en:"Major Ethereum upgrades require:",options_en:["One company's approval","Broad community consensus among developers and validators","Nothing, fully automatic","A bank's approval"]}},
      {id:"eth9", title:"الخصوصية في الإيثريوم", title_en:"Privacy in Ethereum", content_en:"Every transaction and smart contract interaction on Ethereum is fully recorded and public, offering high transparency — but it also means any address linked to your real identity reveals your entire financial and app activity on the network.", content:"كل معاملة وكل تفاعل مع عقد ذكي على إيثريوم مسجّل وعلني بالكامل، ما يمنح شفافية عالية لكنه يعني أيضاً أن أي عنوان مرتبط بهويتك الحقيقية يكشف كامل نشاطك المالي والتطبيقي على الشبكة.", quiz:{q:"معاملات وتفاعلات إيثريوم مع العقود الذكية تكون:",options:["مخفية تماماً","مسجّلة وعلنية بالكامل","محذوفة بعد ساعة","سرية للمدققين فقط"],correct:1,q_en:"Ethereum transactions and smart contract interactions are:",options_en:["Completely hidden","Fully recorded and public","Deleted after an hour","Secret to validators only"]}},
      {id:"eth10", title:"الأمان في الإيثريوم", title_en:"Security in Ethereum", content_en:"The network itself is highly secure thanks to its large number of validators, but individual smart contract security depends on the quality of its code; historical bugs in specific contracts have caused major losses, so it's wise to only interact with audited contracts from trusted sources.", content:"أمان الشبكة نفسها مرتفع جداً بفضل عدد المدققين الكبير، لكن أمان العقود الذكية الفردية يعتمد على جودة برمجتها؛ أخطاء برمجية في عقد معين تسببت تاريخياً بخسائر كبرى، لذا يُنصح بالتفاعل فقط مع عقود مدققة (Audited) من جهات موثوقة.", quiz:{q:"أمان عقد ذكي فردي يعتمد بشكل كبير على:",options:["حجم الشبكة فقط","جودة برمجته","لون واجهة الموقع","عدد المستخدمين فقط"],correct:1,q_en:"The security of an individual smart contract heavily depends on:",options_en:["Network size alone","The quality of its code","The website's color scheme","User count alone"]}}
    ]
  },

  "web3": {
    type: "flat",
    title: "Web3 والمستقبل", title_en: "Web3 & The Future",
    lessons: [
      {id:"w3_1", title:"ما هو Web3؟", title_en:"What Is Web3?", content_en:"Web3 describes the next generation of the internet, where users truly own their data and digital assets via blockchain, instead of large central companies holding them as in today's internet (Web2).", content:"Web3 مصطلح يصف الجيل القادم من الإنترنت، حيث يمتلك المستخدمون بياناتهم وأصولهم الرقمية فعلياً عبر البلوكتشين، بدل أن تحتفظ بها شركات مركزية كبرى كما هو الحال في الإنترنت الحالي (Web2).", quiz:{q:"Web3 يصف بشكل أساسي:",options:["نسخة أقدم من الإنترنت","جيلاً جديداً من الإنترنت يملك فيه المستخدمون بياناتهم عبر البلوكتشين","برنامج تصفح فقط","شبكة تلفزيونية"],correct:1,q_en:"Web3 mainly describes:",options_en:["An older version of the internet","A new generation of the internet where users own their data via blockchain","Just a browser","A TV network"]}},
      {id:"w3_2", title:"الهوية الرقمية والملكية الرقمية", title_en:"Digital Identity & Digital Ownership", content_en:"In Web3, your wallet becomes your unified identity across multiple applications, and your ownership of a digital asset (via an NFT, for example) is recorded directly on the blockchain — not in a company database that can delete or freeze it.", content:"في Web3، محفظتك الرقمية تصبح هويتك الموحدة عبر تطبيقات متعددة، وملكيتك لأصل رقمي (عبر NFT مثلاً) مسجّلة على البلوكتشين مباشرة، لا في قاعدة بيانات شركة يمكنها حذفها أو تجميدها.", quiz:{q:"في Web3، محفظتك الرقمية تعمل كـ:",options:["مجرد تخزين صور","هوية موحدة عبر تطبيقات متعددة","برنامج بريد إلكتروني","لا شيء مهم"],correct:1,q_en:"In Web3, your digital wallet acts as:",options_en:["Just photo storage","A unified identity across multiple apps","An email program","Nothing important"]}},
      {id:"w3_3", title:"الـ DAO والمنصات اللامركزية", title_en:"DAOs & Decentralized Platforms", content_en:"A Decentralized Autonomous Organization (DAO) is a community governed by rules written into smart contracts instead of a traditional executive team, where governance-token holders vote directly on the project's decisions and future.", content:"المنظمة اللامركزية المستقلة (DAO) هي مجتمع يُدار بقواعد مكتوبة في عقود ذكية بدل إدارة تنفيذية تقليدية، حيث يصوّت حاملو توكن الحوكمة مباشرة على قرارات المشروع ومستقبله.", quiz:{q:"الـ DAO تُدار عبر:",options:["مدير تنفيذي تقليدي واحد","قواعد مكتوبة في عقود ذكية يصوّت عليها حاملو التوكن","حكومة مركزية","لا إدارة إطلاقاً"],correct:1,q_en:"A DAO is governed by:",options_en:["One traditional executive manager","Rules in smart contracts voted on by token holders","A central government","No governance at all"]}},
      {id:"w3_4", title:"فرص العمل وصناعة المشاريع", title_en:"Jobs & Building Projects", content_en:"The Web3 sector opened up new career paths: smart contract development, security auditing, tokenomics design, and managing decentralized communities — all skills in growing global demand.", content:"فتح قطاع Web3 مجالات عمل جديدة: تطوير عقود ذكية، تدقيق أمني، تصميم اقتصاديات التوكنات (Tokenomics)، وإدارة مجتمعات لامركزية، وهي مهارات متنامية الطلب عالمياً.", quiz:{q:"من فرص العمل الجديدة في Web3:",options:["تطوير عقود ذكية وتدقيق أمني","الزراعة التقليدية فقط","التوظيف الحكومي فقط","لا فرص جديدة"],correct:0,q_en:"A new job opportunity in Web3 includes:",options_en:["Smart contract development and security auditing","Traditional farming only","Government jobs only","No new opportunities"]}},
      {id:"w3_5", title:"مستقبل الكريبتو والابتكار", title_en:"The Future of Crypto & Innovation", content_en:"The sector is heading toward deeper integration with traditional finance, better scalability and lower fees via Layer 2 solutions, and increasing government regulation that may grant broader legitimacy but also imposes new rules worth following closely.", content:"يتجه القطاع نحو دمج أعمق مع التمويل التقليدي، وتحسين قابلية التوسع وخفض الرسوم عبر حلول الطبقة الثانية، وتزايد التنظيم الحكومي الذي قد يمنح شرعية أوسع لكنه يفرض أيضاً قيوداً جديدة يجب متابعتها باستمرار.", quiz:{q:"من الاتجاهات المستقبلية المتوقعة للقطاع:",options:["اختفاء الكريبتو تماماً","تحسين قابلية التوسع وخفض الرسوم عبر حلول الطبقة الثانية","إلغاء كل التنظيم الحكومي","توقف كل الابتكار"],correct:1,q_en:"An expected future trend for the sector:",options_en:["Crypto disappearing entirely","Better scalability and lower fees via Layer 2 solutions","All government regulation disappearing","All innovation stopping"]}}
    ]
  },

  "defi": {
    type: "flat",
    title: "التمويل اللامركزي DeFi", title_en: "Decentralized Finance (DeFi)",
    lessons: [
      {id:"defi1", title:"ما هو DeFi؟", title_en:"What Is DeFi?", content_en:"DeFi (decentralized finance) is a set of financial applications — lending, borrowing, trading — that run via smart contracts directly between users, with no bank or middleman company controlling your money or deciding who can access the service.", content:"DeFi (التمويل اللامركزي) هو مجموعة تطبيقات مالية (إقراض، اقتراض، تبادل) تعمل عبر عقود ذكية مباشرة بين المستخدمين، بدون بنك أو شركة وسيطة تتحكم بأموالك أو تقرر من يمكنه الوصول للخدمة.", quiz:{q:"DeFi يقدّم خدمات مالية عبر:",options:["بنوك تقليدية فقط","عقود ذكية مباشرة بين المستخدمين","حكومات مركزية","لا شيء تقني"],correct:1,q_en:"DeFi delivers financial services through:",options_en:["Traditional banks only","Smart contracts directly between users","Central governments","Nothing technical"]}},
      {id:"defi2", title:"الإقراض والاقتراض والربح من السيولة", title_en:"Lending, Borrowing, and Earning from Liquidity", content_en:"In DeFi you can deposit your coins into a lending protocol to earn interest from other borrowers, or provide liquidity to a decentralized exchange and earn a share of trading fees — with no human intermediary running the process.", content:"يمكنك في DeFi إيداع عملاتك في بروتوكول إقراض لتكسب فائدة من مقترضين آخرين، أو توفير سيولة لمنصة تبادل لامركزية وكسب جزء من رسوم التداول، دون وسيط بشري يدير العملية.", quiz:{q:"توفير السيولة لمنصة DeFi يمكن أن يكسبك:",options:["لا شيء إطلاقاً","جزءاً من رسوم التداول","عملة مجانية مضمونة دائماً","إلغاء الرسوم البنكية"],correct:1,q_en:"Providing liquidity to a DeFi platform can earn you:",options_en:["Nothing at all","A share of trading fees","Guaranteed free coins always","Cancelled bank fees"]}},
      {id:"defi3", title:"المخاطر وكيفية التعامل معها", title_en:"Risks and How to Handle Them", content_en:"DeFi risks include: smart contract bugs, sharp price volatility that can force a liquidation of your loan, and slick-looking scam projects. Reduce risk by spreading funds across several trusted protocols instead of putting everything in one place.", content:"تشمل مخاطر DeFi: ثغرات برمجية في العقود الذكية، تقلب الأسعار الحاد الذي قد يسبب تصفية قسرية لقرضك، ومشاريع احتيالية بواجهة براقة. قلّل المخاطرة بالتوزيع بين عدة بروتوكولات موثوقة وعدم استثمار كل أموالك بمكان واحد.", quiz:{q:"من أبرز مخاطر DeFi:",options:["استقرار سعري تام دائماً","ثغرات برمجية في العقود الذكية","ضمان حكومي كامل","لا مخاطر إطلاقاً"],correct:1,q_en:"A key risk of DeFi is:",options_en:["Always perfect price stability","Bugs/exploits in smart contracts","Full government guarantee","No risk at all"]}},
      {id:"defi4", title:"العقود الذكية في DeFi", title_en:"Smart Contracts in DeFi", content_en:"Every action in DeFi, from deposit to withdrawal, runs through a pre-programmed smart contract with no human involved — meaning full transparency in the rules, but also that any coding bug becomes a permanent vulnerability if not caught early.", content:"كل عملية في DeFi، من الإيداع إلى السحب، تُنفَّذ عبر عقد ذكي مبرمج مسبقاً بدون تدخل بشري، وهذا يعني شفافية كاملة في القواعد، لكنه يعني أيضاً أن أي خطأ برمجي في العقد يصبح ثغرة دائمة إن لم تُكتشف مبكراً.", quiz:{q:"كل عملية في DeFi (إيداع، سحب) تُنفَّذ عبر:",options:["موظف بنك بشري","عقد ذكي مبرمج مسبقاً","مكالمة هاتفية","لا شيء آلي"],correct:1,q_en:"Every DeFi operation (deposit, withdrawal) executes via:",options_en:["A human bank employee","A pre-programmed smart contract","A phone call","Nothing automated"]}},
      {id:"defi5", title:"منصات ومشاريع DeFi", title_en:"DeFi Platforms and Projects", content_en:"Popular DeFi project categories include decentralized exchanges (DEX), lending protocols, and automated yield aggregators. Before using any platform, check its age, security audits, and the amount of liquidity it manages.", content:"من أشهر فئات مشاريع DeFi: منصات التبادل اللامركزي (DEX)، بروتوكولات الإقراض، ومنصات العائد الآلي (Yield Aggregators). قبل استخدام أي منصة، تحقق من عمرها، تدقيقها الأمني، وحجم السيولة المُدارة فيها.", quiz:{q:"قبل استخدام أي منصة DeFi، يُنصح بالتحقق من:",options:["لون الموقع فقط","عمرها وتدقيقها الأمني وحجم السيولة","اسم المؤسس فقط دون شيء آخر","لا حاجة للتحقق من شيء"],correct:1,q_en:"Before using any DeFi platform, you should check:",options_en:["Just the website's color","Its age, security audit, and liquidity size","Only the founder's name","No need to check anything"]}}
    ]
  },

  "stablecoins": {
    type: "flat",
    title: "العملات المستقرة Stablecoins", title_en: "Stablecoins",
    lessons: [
      {id:"sc1", title:"ما هي العملات المستقرة؟", title_en:"What Are Stablecoins?", content_en:"A stablecoin is a cryptocurrency designed to hold a roughly fixed value, usually pegged 1:1 to a traditional currency like the US dollar, maintained through a cash reserve or an algorithmic mechanism.", content:"العملة المستقرة (Stablecoin) هي عملة رقمية مصممة لتحافظ على قيمة ثابتة تقريباً، غالباً مربوطة بعملة تقليدية مثل الدولار الأمريكي بنسبة واحد لواحد، وذلك عبر احتياطي نقدي أو آلية خوارزمية تحافظ على هذا الربط.", quiz:{q:"العملة المستقرة مصممة لـ:",options:["التقلب الشديد يومياً","الحفاظ على قيمة شبه ثابتة، غالباً مربوطة بالدولار","الاختفاء بعد شهر","استبدال الذهب فقط"],correct:1,q_en:"A stablecoin is designed to:",options_en:["Fluctuate wildly daily","Hold a near-fixed value, often pegged to the dollar","Disappear after a month","Replace gold only"]}},
      {id:"sc2", title:"الفرق بين العملات المستقرة والعملات الرقمية الأخرى", title_en:"Stablecoins vs. Other Cryptocurrencies", content_en:"Unlike Bitcoin or Ethereum, which swing sharply in price, a stablecoin holds a near-constant value, making it a practical tool for transfers and saving within the crypto world without exposure to volatility risk.", content:"بعكس بيتكوين أو إيثريوم اللذين يتقلب سعرهما بشدة، تحافظ العملة المستقرة على سعر شبه ثابت، ما يجعلها أداة عملية للتحويلات والادخار داخل عالم الكريبتو دون التعرض لمخاطر التقلب.", quiz:{q:"مقارنة بالبيتكوين، العملة المستقرة عادة:",options:["أكثر تقلباً بكثير","أقل تقلباً وأكثر ثباتاً بالسعر","بلا أي استخدام عملي","غير متاحة للتحويل"],correct:1,q_en:"Compared to Bitcoin, a stablecoin is usually:",options_en:["Far more volatile","Less volatile and more price-stable","With no practical use","Untransferable"]}},
      {id:"sc3", title:"الاستخدامات العملية", title_en:"Practical Uses", content_en:"Stablecoins are used for fast cross-border transfers, as a temporary safe haven during market volatility without fully exiting to traditional currency, and as a payment method in DeFi apps without exposure to price-swing risk.", content:"تُستخدم العملات المستقرة للتحويلات السريعة عبر الحدود، كملاذ مؤقت أثناء تقلبات السوق دون الخروج لعملة تقليدية، وكوسيلة دفع في تطبيقات DeFi دون التعرض لمخاطرة تقلب السعر.", quiz:{q:"من الاستخدامات العملية للعملات المستقرة:",options:["التحويلات السريعة عبر الحدود","تخزين الصور فقط","إلغاء الإنترنت","لا استخدام لها"],correct:0,q_en:"A practical use of stablecoins is:",options_en:["Fast cross-border transfers","Storing photos only","Cancelling the internet","No use at all"]}},
      {id:"sc4", title:"المشاريع الشهيرة والآفاق المستقبلية", title_en:"Popular Projects and Future Outlook", content_en:"The most famous stablecoins are USDT and USDC, both pegged to the dollar. The sector is heading toward broader government regulation to ensure real transparency of the reserves backing each issued coin, especially after past cases raised doubts about some projects.", content:"من أشهر العملات المستقرة: USDT وUSDC المرتبطتان بالدولار. يتجه القطاع نحو تنظيم حكومي أوسع لضمان شفافية الاحتياطي الفعلي خلف كل عملة مصدرة، خصوصاً بعد حالات سابقة أثارت شكوكاً حول بعض المشاريع.", quiz:{q:"من أشهر أمثلة العملات المستقرة المرتبطة بالدولار:",options:["Dogecoin","USDT وUSDC","Bitcoin","Ethereum"],correct:1,q_en:"A well-known example of a dollar-pegged stablecoin:",options_en:["Dogecoin","USDT and USDC","Bitcoin","Ethereum"]}}
    ]
  },

  "security": {
    type: "flat",
    title: "الأمان وحماية الأصول", title_en: "Security & Asset Protection",
    lessons: [
      {id:"sec1", title:"أنواع الاحتيال في الكريبتو", title_en:"Types of Crypto Scams", content_en:"Common scams include: phishing sites impersonating real platforms, \"rug pull\" projects where founders vanish after raising funds, and messages promising to double your money if you send it to a certain address first.", content:"من أشهر أنواع الاحتيال: مواقع تصيّد تنتحل شكل منصات حقيقية، مشاريع 'اسحب البساط' (Rug Pull) التي يختفي مؤسسوها بعد جمع الأموال، ورسائل تعد بمضاعفة أموالك مقابل إرسالها أولاً لعنوان معين.", quiz:{q:"مشروع 'اسحب البساط' (Rug Pull) يعني:",options:["مشروع طويل الأمد موثوق","مؤسسون يختفون بعد جمع أموال المستثمرين","نوع من المحافظ الباردة","تحديث أمني رسمي"],correct:1,q_en:"A \"Rug Pull\" project means:",options_en:["A long-term trustworthy project","Founders vanish after collecting investor funds","A type of cold wallet","An official security update"]}},
      {id:"sec2", title:"حماية المحافظ والحسابات", title_en:"Protecting Wallets and Accounts", content_en:"Enable two-factor authentication on every account linked to crypto, store your recovery phrase physically offline, and never type it into any website or pop-up, no matter how official it looks.", content:"فعّل التحقق بخطوتين على كل حساب مرتبط بالكريبتو، احفظ عبارة الاسترداد بشكل مادي غير رقمي بعيداً عن الإنترنت، ولا تُدخلها أبداً في أي موقع أو نافذة منبثقة مهما بدت رسمية.", quiz:{q:"عبارة الاسترداد (Seed Phrase) يجب أن:",options:["تُشارك مع الدعم الفني فوراً","تُحفظ مادياً بعيداً عن الإنترنت ولا تُشارك أبداً","تُكتب في ملاحظات الهاتف","تُنشر على تويتر"],correct:1,q_en:"Your seed phrase should be:",options_en:["Shared with support immediately","Kept physically offline and never shared","Written in phone notes","Posted on Twitter"]}},
      {id:"sec3", title:"التحقق من المشاريع والرموز", title_en:"Verifying Projects and Tokens", content_en:"Before investing in any project, check for a publicly known team, auditable source code, a security audit from a reputable firm, and realistic promised returns — any guarantee of huge, certain profit is a strong warning sign.", content:"قبل الاستثمار في أي مشروع، تحقق من هوية الفريق العلنية، وجود كود مصدري قابل للتدقيق، سجل تدقيق أمني من جهة معروفة، وواقعية العوائد المعروضة — أي وعد بربح مضمون وضخم هو علامة تحذير قوية.", quiz:{q:"علامة تحذير قوية عند تقييم مشروع كريبتو:",options:["فريق عمل معروف وموثق","وعد بعوائد مضمونة وضخمة بسرعة","كود مصدري مفتوح للتدقيق","تقارير تقنية دورية"],correct:1,q_en:"A strong warning sign when evaluating a crypto project:",options_en:["A known, documented team","A promise of guaranteed, huge, fast returns","Open-source code for auditing","Regular technical reports"]}},
      {id:"sec4", title:"عقلية الأمان للمستثمرين والمتداولين", title_en:"A Security Mindset for Investors and Traders", content_en:"Security isn't just a technical tool — it's a habit of mind: slow down before any emotional decision, verify every link you open, and don't let fear of missing out (FOMO) push you to skip your usual security steps.", content:"الأمان ليس أداة تقنية فقط بل عادة ذهنية: تمهّل قبل أي قرار عاطفي، تحقق من كل رابط تفتحه، ولا تدع الخوف من فوات الفرصة (FOMO) يدفعك لتجاوز خطواتك الأمنية المعتادة.", quiz:{q:"الأمان في الكريبتو يعتمد بشكل كبير على:",options:["الحظ فقط","عادات ذهنية مثل التمهل والتحقق قبل القرار","تجاهل كل الروابط والرسائل","لا شيء يمكن فعله"],correct:1,q_en:"Security in crypto heavily depends on:",options_en:["Luck alone","Mental habits like slowing down and verifying before deciding","Ignoring all links and messages","Nothing you can do"]}}
    ]
  },

  "networks": {
    type: "flat",
    title: "الشبكات", title_en: "Networks",
    lessons: [
      {id:"net1", title:"ما هي الشبكات", title_en:"What Are Networks", content_en:"A blockchain network is the infrastructure a coin or set of applications runs on. Networks vary in speed, fees, and degree of decentralization; choosing the right one directly affects your experience and cost.", content:"شبكة البلوكتشين هي البنية التحتية التي تعمل عليها عملة أو مجموعة تطبيقات، وتتفاوت الشبكات في سرعتها، رسومها، ومستوى لامركزيتها؛ اختيار الشبكة المناسبة يؤثر مباشرة على تجربتك وتكلفتك.", quiz:{q:"شبكة البلوكتشين هي:",options:["نوع من العملات فقط","البنية التحتية التي تعمل عليها عملة أو تطبيقات","برنامج محاسبة","لا علاقة لها بالكريبتو"],correct:1,q_en:"A blockchain network is:",options_en:["Just a type of coin","The infrastructure a coin or apps run on","Accounting software","Unrelated to crypto"]}},
      {id:"net2", title:"ما الفرق بينها", title_en:"What's the Difference Between Them", content_en:"Networks differ in their consensus mechanism (Proof of Work or Proof of Stake), transactions per second, and degree of decentralization; a faster network often trades off some decentralization — known as the \"blockchain trilemma.\"", content:"تختلف الشبكات في آلية الإجماع المستخدمة (إثبات عمل أو إثبات حصة)، عدد المعاملات بالثانية، ودرجة اللامركزية؛ شبكة أسرع غالباً ما تضحي بجزء من اللامركزية، وهذا يُعرف بـ'ثلاثية البلوكتشين المستحيلة'.", quiz:{q:"الشبكات تختلف فيما بينها من ناحية:",options:["اللون فقط","آلية الإجماع وعدد المعاملات بالثانية ودرجة اللامركزية","اسم المطور فقط","لا فرق بينها إطلاقاً"],correct:1,q_en:"Networks differ from each other in:",options_en:["Color only","Consensus mechanism, transactions per second, and decentralization level","Developer name only","No difference at all"]}},
      {id:"net3", title:"ما هي الأعلى والأقل تكلفة", title_en:"The Most and Least Expensive", content_en:"Base networks like Ethereum can have higher fees during congestion, while Layer 2 solutions or some newer independent networks offer much lower fees — often at the cost of a less battle-tested degree of decentralization or security so far.", content:"شبكات مثل إيثريوم الأساسية تكون رسومها أعلى وقت الازدحام، بينما شبكات الطبقة الثانية أو بعض الشبكات المستقلة الحديثة توفر رسوماً أقل بكثير، لكن غالباً بمقابل درجة لامركزية أو أمان أقل رسوخاً حتى الآن.", quiz:{q:"شبكات الطبقة الثانية غالباً توفر:",options:["رسوماً أعلى دائماً","رسوماً أقل بكثير من الشبكة الأساسية وقت الازدحام","إلغاء الرسوم كلياً للأبد","لا فرق بالتكلفة"],correct:1,q_en:"Layer 2 networks generally offer:",options_en:["Always higher fees","Much lower fees than the base network during congestion","Fees eliminated forever","No cost difference"]}},
      {id:"net4", title:"ما هي الشبكات الأكثر أماناً", title_en:"The Most Secure Networks", content_en:"Generally, older networks with the most distributed participation (like Bitcoin and Ethereum) are considered the most secure and time-tested, while newer networks may offer better performance but with a shorter security track record.", content:"عموماً، الشبكات الأقدم والأكثر توزعاً من حيث عدد المشاركين (مثل بيتكوين وإيثريوم) تُعتبر الأكثر أماناً واختباراً بمرور الوقت، بينما الشبكات الأحدث قد تقدم أداءً أفضل لكن بسجل أمان أقصر.", quiz:{q:"الشبكات الأقدم والأكثر توزعاً تُعتبر عموماً:",options:["الأقل أماناً","الأكثر أماناً واختباراً بمرور الوقت","بلا أي مستخدمين","غير قابلة للاستخدام"],correct:1,q_en:"Older, more distributed networks are generally considered:",options_en:["The least secure","The most secure and battle-tested over time","Without any users","Unusable"]}},
      {id:"net5", title:"لماذا تعلم الشبكات مهم", title_en:"Why Learning About Networks Matters", content_en:"Understanding the network you're using protects you from costly mistakes, like sending a coin on the wrong network and losing it permanently, and helps you pick the right network for your goal: lower fees, higher speed, or maximum security.", content:"فهم الشبكة التي تستخدمها يحميك من أخطاء مكلفة، مثل إرسال عملة على شبكة خاطئة فتُفقد للأبد، ويساعدك على اختيار الشبكة الأنسب لهدفك: رسوم أقل، سرعة أعلى، أو أمان أقصى حسب حاجتك.", quiz:{q:"إرسال عملة على شبكة خاطئة قد يؤدي إلى:",options:["لا شيء، تصل دائماً بأمان","فقدان العملة للأبد غالباً","مضاعفة المبلغ تلقائياً","تحويلها لعملة أخرى مجاناً"],correct:1,q_en:"Sending a coin on the wrong network can lead to:",options_en:["Nothing, it always arrives safely","Often permanently losing the funds","Automatically doubling the amount","Free conversion to another coin"]}}
    ]
  },

  "dex-cex": {
    type: "flat",
    title: "منصات DEX و CEX", title_en: "DEX & CEX Platforms",
    lessons: [
      {id:"dc1", title:"ما هي منصات DEX", title_en:"What Are DEX Platforms", content_en:"Decentralized exchange (DEX) platforms let you trade directly from your own wallet via smart contracts, with no company holding your funds — Uniswap and PancakeSwap are well-known examples.", content:"منصات التبادل اللامركزي (DEX) تتيح لك التداول مباشرة من محفظتك الشخصية عبر عقود ذكية، دون تسليم أموالك لأي شركة وسيطة، وأشهرها Uniswap وPancakeSwap.", quiz:{q:"منصات DEX تتيح التداول:",options:["فقط عبر موظف بشري","مباشرة من محفظتك الشخصية عبر عقود ذكية","بعد إرسال هويتك فقط","لا تداول إطلاقاً"],correct:1,q_en:"DEX platforms let you trade:",options_en:["Only through a human employee","Directly from your own wallet via smart contracts","Only after submitting your ID","No trading at all"]}},
      {id:"dc2", title:"كيف تعمل منصات DEX", title_en:"How DEX Platforms Work", content_en:"Most DEX platforms rely on an \"automated market maker\" (AMM): other users deposit pairs of coins into a liquidity pool, and when you trade, the smart contract automatically sets the price based on the ratio of the two coins in that pool.", content:"تعتمد أغلب منصات DEX على 'صانع سوق آلي' (AMM): مستخدمون آخرون يودعون أزواج عملات في مجمّع سيولة، وحين تتداول أنت، يحدد العقد الذكي السعر تلقائياً بناءً على نسبة العملتين في ذلك المجمّع.", quiz:{q:"أغلب منصات DEX تعتمد على:",options:["موظف بشري لتحديد السعر","صانع سوق آلي (AMM) ومجمّعات سيولة","اتصال هاتفي مباشر","لا آلية محددة"],correct:1,q_en:"Most DEX platforms rely on:",options_en:["A human employee to set price","An automated market maker (AMM) and liquidity pools","A direct phone call","No defined mechanism"]}},
      {id:"dc3", title:"ما هي منصات CEX", title_en:"What Are CEX Platforms", content_en:"Centralized exchange (CEX) platforms like Binance and Coinbase act as an intermediary company that manages your account and executes your trades on your behalf, offering high liquidity and an easy interface, but requiring you to hand over custody of your funds.", content:"منصات التبادل المركزي (CEX) مثل بينانس وكوين بيس تعمل كشركة وسيطة تدير حساباتك وتنفّذ صفقاتك نيابة عنك، وتوفر سيولة عالية وواجهة سهلة، لكنها تتطلب تسليم أموالك لحفظها لديها.", quiz:{q:"منصات CEX مثل بينانس تعمل كـ:",options:["شركة وسيطة تدير حساباتك","محفظة باردة فقط","عقد ذكي بلا شركة","لا شيء، مجرد موقع إخباري"],correct:0,q_en:"CEX platforms like Binance act as:",options_en:["An intermediary company managing your accounts","Just a cold wallet","A smart contract with no company","Nothing, just a news site"]}},
      {id:"dc4", title:"كيف تعمل CEX", title_en:"How CEX Platforms Work", content_en:"On a CEX, you deposit funds into an account managed by the platform, and your trades execute through an \"order book\" that instantly matches buy and sell requests among thousands of users, with the platform itself guaranteeing execution and settlement.", content:"عند التداول على CEX، تودع أموالك في حساب تديره المنصة، وتُنفَّذ صفقاتك عبر 'دفتر أوامر' يطابق طلبات البيع والشراء بين آلاف المستخدمين لحظياً، والمنصة نفسها هي الضامن لتنفيذ الصفقة وتسويتها.", quiz:{q:"صفقات CEX تُنفَّذ عبر:",options:["دفتر أوامر يطابق طلبات البيع والشراء","عملة واحدة ثابتة فقط","لا آلية محددة","اتصال بريدي بطيء"],correct:0,q_en:"CEX trades are executed via:",options_en:["An order book matching buy/sell requests","Only one fixed coin","No defined mechanism","Slow postal mail"]}},
      {id:"dc5", title:"ما الفرق بينهما", title_en:"What's the Difference Between Them", content_en:"The core difference: a DEX gives you full control of your funds but requires more technical skill and can be slower during congestion, while a CEX is easier and faster for beginners but requires full trust in the platform and its policies.", content:"الفرق الجوهري: DEX تمنحك تحكماً كاملاً بأموالك لكن تتطلب خبرة تقنية أعلى وقد تكون أبطأ في أوقات الازدحام، بينما CEX أسهل وأسرع للمبتدئين لكنها تتطلب ثقة كاملة بالمنصة نفسها وسياساتها.", quiz:{q:"الفرق الجوهري بين DEX و CEX:",options:["لا فرق إطلاقاً","DEX تحكم كامل بأموالك، CEX تتطلب ثقة كاملة بالمنصة","CEX غير قانونية دائماً","DEX أبطأ من CEX دائماً بلا استثناء"],correct:1,q_en:"The core difference between DEX and CEX:",options_en:["No difference at all","DEX gives full control of your funds, CEX requires full trust in the platform","CEX is always illegal","DEX is always slower than CEX, no exceptions"]}},
      {id:"dc6", title:"كيفية التسجيل", title_en:"How to Sign Up", content_en:"Signing up for a CEX usually requires an email and identity verification (KYC). To trade on a DEX, you don't need traditional sign-up at all — just connect a wallet you already have directly to the platform.", content:"للتسجيل في CEX تحتاج غالباً بريداً إلكترونياً وتحقق هوية (KYC). أما للتداول على DEX فلا تحتاج تسجيلاً تقليدياً إطلاقاً — فقط اربط محفظتك الرقمية الموجودة مسبقاً مباشرة بالمنصة.", quiz:{q:"للتسجيل في منصة CEX عادة تحتاج:",options:["لا شيء إطلاقاً","بريداً إلكترونياً وتحقق هوية (KYC)","محفظة باردة فقط","لا تحتاج بريداً إلكترونياً أبداً"],correct:1,q_en:"To register on a CEX you typically need:",options_en:["Nothing at all","An email and identity verification (KYC)","Only a cold wallet","Never need an email"]}}
    ]
  }

};
